### PR TITLE
Move to antitypical Result type

### PR DESCRIPTION
**Pull request by petester42**
As discussed in #338, this move to using the standard result type instead of creating our own. Due to Alamofire having its own result type I had to move some things around to remove the name clashing. I had to move things to other files since the antitypical result type cannot be prefixed since the name of the framework is `Result` and using `Result.Result` gives a compiler error.

This should work with cocoapods just fine but there seems to be issues with carthage. ReactiveCocoa versions give errors for tvOS and watchOS targets since the minimum deployment target is now 2.1 and 9.1 respectively instead of 2.0 and 9.0. The same thing happens with the RxSwift version for tvOS. Maybe there was a change in Xcode 7.2 that causes this problem or these frameworks don't have the proper setting for the minimum deployment target anymore. This needs investigation.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool, thanks for looking into this. We could certainly just bump up out minimum deployment versions. Anyone else free to help on this?

**Comment by Austinate** [comment]
I can try to bring proper solution

**Comment by petester42** [comment]
The update to ReactiveCocoa 4 RC1 fixes the reactive cocoa issues. The RxSwift issue still happens but I'm pretty sure its on their side now.

**Comment by mpurland** [comment]
Did bumping to RC1 fix the issue?

**Comment by petester42** [comment]
@mpurland yes it did. thanks. The same issue is happening with RxSwift but I sent them a fix.

**Comment by petester42** [comment]
This should be good to go with the update to rxswift :tada:

**Comment by ashfurrow** [comment]
Looks good to me!

**Pull request merged**
