### PR TITLE
Upgrade to RxSwift 5.1

### PR DESCRIPTION
**Pull request by jdisho**
Since we have an important update from [RxSwift](https://github.com/ReactiveX/RxSwift/releases/tag/5.1.0), I'm upgrading it to the latest version, [5.1](https://github.com/ReactiveX/RxSwift/releases/tag/5.1.0) and bumping `Moya.podspec` version to `14.1.0`

This upgrade does not introduce any breaking changes. 

Closing #2003

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@jdisho Changes looks good 👍 But I think we need to add a changelog entry for that :)

**Comment by sunshinejr** [comment]
@LucianoPAlmeida I will hold on this for a sec since this PR shouldn't really be needed as we have a bit loosely tightened the constraint for deps (~> 5.0 should be able to update to 5.1). More in the issue mentioned in the PR.

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida I will hold on this for a sec since this PR shouldn't really be needed as we have a bit loosely tightened the constraint for deps (~> 5.0 should be able to update to 5.1). More in the issue mentioned in the PR.

@sunshinejr Sure! :)

**Comment by sunshinejr** [comment]
@jdisho seems like we don't need to bump the version for now, the problem in the original issue was resolved - in that case I'm gonna close the issue. Thank you though for a very fast PR! 🙏

**Pull request closed without merging**
