### PR TITLE
Updated project to support Carthage

### PR DESCRIPTION
**Pull request by justinmakaila**
This PR adds full support for Carthage, and a solution to using `RxSwift` and `ReactiveCocoa` without mandating it for those who wish to use pure `Moya`.

 - Adds `ReactiveMoya` and `RxMoya` targets
 - Adds RAC 3.0 support to `ReactiveCocoaMoyaProvider`
 - Expands the example project to include demonstrations using reactive extensions

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks a lot, Justin! It's a huge PR – I'll take a look at it this weekend. If any other contributors could lend a hand, that'd be :+1: 

Justin, could I please ask you to mark these improvements in the changelog? I see you've already updated the README – awesome :tada: 

The tests are failing – looks like a Circle configuration problem around the Demo workspace. Any ideas?

**Comment by justinmakaila** [comment]
No idea, I've never worked with circle before. I'll take a look and get back to you about that



—Justin Makaila

**Comment by colinta** [comment]
1,054 files!?  That's... *ahem* a bit alarming.

It looks like all these files are mostly build artifacts.  Looking at other projects that support Carthage & CocoaPods, they don't include a `Carthage/` folder that contains all the build headers.  I'm looking in particular at https://github.com/thoughtbot/argo

I'm wondering: can that entire folder be removed?  From what I understand about Carthage, it's a minimalist system, it seems like a red flag that all these header files are included here.

**Comment by justinmakaila** [comment]
Yes, we could remove it. I pushed the Carthage/build dir so you can use the demo without running Carthage



—Justin Makaila

**Comment by colinta** [comment]
Ah I see.  Well obv my vote is to keep the repo lighter.  Might make sense, then, to add something to the README about building, but I think people that use Carthage already can figure it out :-)

**Comment by justinmakaila** [comment]
@colinta I'm with you completely, I just didn't want to introduce a PR with less functionality than the previous version. Ultimately, the decision is up to @ashfurrow and the core team, and I'm open to modifying this PR to match the requirements!

**Comment by colinta** [comment]
Are you saying the demos won't even run if the user doesn't use Carthage?

**Comment by orta** [comment]
It's common to check in the Pods directory for libraries, so this is duplicating all of that too: https://github.com/ashfurrow/Moya/tree/master/Demo/Pods

Personally, I'd remove both of them, and in the README tell people if they want to demo it run `pod try Moya`.  It's a huge amount of additional files for a lib that's probably 6-8 swift files big in reality.

**Comment by justinmakaila** [comment]
@orta I'm with you on that. Not a huge fan of pushing things just for the sake of an example project.

I'm going to make the adjustments for the circle build, and then make the modifications I need to to get `pod try Moya` to work. I think broke that in my haste of ripping everything out early on.

**Comment by orta** [comment]
`pod try https://github.com/justinmakaila/Moya/` will let you test. You need to add a working Podfile to the Example dir, [this](https://github.com/ashfurrow/Moya/blob/master/Demo/Podfile) will probably do it.

**Comment by ashfurrow** [comment]
Yeah, I think it's time to separate out the demo from the library repo. 

I only included the Pods directory because I was told it was necessary for Carthage support. If someone were interested in writing a how-to blog post about supporting Carthage and CocoaPods, that would probably be a great service to the open source community. As a library owner, I remain confused about how my own library is structured and why. It's not a comfortable feeling.

**Comment by ashfurrow** [comment]
This could be rolled into #168 where we could have a Demo repo for both Carthage and CocoaPods, separate from the main repo.

**Comment by orta** [comment]
Downside of that is `pod try Moya` doesn't work

**Comment by ashfurrow** [comment]
How so? Never used pod try before.

**Comment by orta** [comment]
It will go to the Moya podspec, find it's repo, download it and look for an xcodeproj + podfile. Separating the demo repo from the lib repo would make that tough.

**Comment by justinmakaila** [comment]
Can we link the library to the demo repo some how? `git submodule`s or something?

**Comment by orta** [comment]
Not right now, https://github.com/CocoaPods/cocoapods-try/issues/38

**Comment by justinmakaila** [comment]
I mean, we could move the demo project to a separate project, pushing a `Carthage/Build` dir there, which would allow people to just clone and run.

Obviously, this isn't ideal, because `pod try` is a sweet way to handle that.

**Comment by orta** [comment]
I don't think moving the example to a separate repo is a good idea, other libraries don't do this. 

I'd move the `Pods` and the Carthage-whatever directories into `.gitignore` then add a note in the README that if you want to run the example you have to go to the example folder and run `pod install` or `carthage install`. Or for the no-effort approach `pod try Moya`. Again, this isn't some mega-huge library with thousands of moving parts.

**Comment by justinmakaila** [comment]
I’m going to add that to this PR.




Though, because this is such a small library, I think it’s perfect to try to optimize for these cases, so bigger libraries can follow suit. 


—Justin Makaila

**Comment by justinmakaila** [comment]
So this is just about ready to go, I just want to get the CI to build successfully.

**Comment by ashfurrow** [comment]
Amazing! Let me know if I can lend a hand. Thanks again! :boom:

**Comment by ashfurrow** [comment]
Hey @justinmakaila – would it be possible to have the Example app and tests still built using CocoaPods?

**Comment by justinmakaila** [comment]
@ashfurrow It'd be possible, but all of that would have to be redone. As it stands:

To run the example:
1. Run `carthage update` in the root
2. Open `Moya.xcworkspace` and set your target to `MoyaExample` OR open `Example/MoyaExample.xcodeproj`
3. Run.

To execute tests:
1. Run `carthage update` in the root (if you haven't already)
2. Open `Moya.xcworkspace` or `Moya.xcodeproj` and set your target to `Moya Tests`
3. Run

**Comment by ashfurrow** [comment]
So Carthage relies on the Moya xcodeproject? I thought CocoaPods was generating one for us now. Sorry if I'm showing my ignorance here – I'm sure you can understand my hesitation to make Moya depend on an unfamiliar tool.

**Comment by justinmakaila** [comment]
Yes. CocoaPods was symlinking to the Pods project, but I found it to be overkill. I totally understand your hesitation, and want to do everything I can to make the transition simple, and answer any questions you have along the way.

**Comment by ashfurrow** [comment]
OK, so. Touchy subject for some – I want anyone reading this to know that I have a lot of respect for the developers who've build Carthage, for @justinmakaila and @neonichu who have done so much work to support Carthage in Moya, and for developers using Moya. If someone tries to turn this into a flamewar, I'll be very disappointed in them. 

:heart: 

Ok! So Moya actually predates Carthage by a few months – Moya was build as a CocoaPod, which the capabilities and limitations of that tool in mind. 

Carthage was released, and people asked for Carthage support on Moya. I didn't know how to add it, but several contributors offered to help, which is fantastic :smile_cat: They asked for help from Carthage, but their developers said that subspec-like functionality [conflicts with their philosophy](https://github.com/Carthage/Carthage/issues/588#issuecomment-116137295). 

Undeterred, @justinmakaila and others laboured to come up with a solution that worked for both tools, requiring Moya to compromise on the original library structure (informed by CocoaPods). At last, we'd nearly accomplished this herculean task. 

My remaining issue is that this PR fundamentally changes Moya from a CocoaPod that could support Carthage, to a Carthage library that can incidentally be used with CocoaPods. This might seem like a trivial matter, and it's at this point that I need to recognize that _I_ no longer own Moya – the community does. My own feelings matter a lot less.

But the community has been using Moya _as_ a CocoaPod for its entire lifetime, and a change of this foundational nature needs to be considered carefully. 

Respectfully, Justin, I think the Demo, unit tests, CI, and all that stuff should remain built atop CocoaPods. I realize this undoes some of the work you've put into this, so I'd like to do the work: I'll check out your fork, get Moya working atop CocoaPods again, ensure that Carthage support still works, then send a PR back into your branch so you can review my changes. Does that sound OK to you? We can hop on a google hangout to discuss this in person, too!

**Comment by colinta** [comment]
I'm glad the focus is remaining on CocoaPods.  I think Carthage is a great tool, but since most users aren't clamoring for supporting it, I think we'd be doing a disservice if CocoaPods was made a second class citizen.

**Comment by ashfurrow** [comment]
Hey! This is still on my radar, just got sidetracked. 

As for the code structure, having the separate repos like https://github.com/Moya/ReactiveMoya is fine for _code_, but I think it's a good idea to keep all documentation and issue tracking in this main repo. This will keep the barrier to entry low (someone learning to use Moya shouldn't have to know how we structure our code to read our docs). Any objections?

**Comment by justinmakaila** [comment]
None here



—Justin Makaila

**Comment by zbeckman** [comment]
I agree – as someone that definitely falls into the "new user" category. I'm just now trying to get Moya, ReactiveCocoa, and Alamofire working together... and the fewer things I have to hunt down and figure out, the better. I also vote for keeping a focus on CocoaPods. I have one Carthage module (because they don't have a pod yet... but should soon). Pods work much better for us, in a distributed project.

**Comment by ashfurrow** [comment]
Alrighty, I've disabled issues on the other repositories. We also need to update their READMEs to point to this repository. These other repos are basically just places to store files.

If we're centralizing docs here, I think it makes sense to centralize tests here as well. I can't see that being a problem with Carthage – @justinmakaila does that sound OK?

**Comment by justinmakaila** [comment]
As long as the reactive repositories can be imported into the test suite without naming collisions (They both have their product names set to “Moya”). 


—Justin Makaila

**Comment by ashfurrow** [comment]
Shouldn't be a problem – we're restructuring the tests to run under CocoaPods, which won't have that problem.

**Comment by justinmakaila** [comment]
👍🏻



—Justin Makaila

**Comment by ashfurrow** [comment]
Orta and I have implemented a solution that doesn't require us to split up the source code into three separate repositories, which I've PR'd in #215. @justinmakaila thank you so much for your work on this :smile_cat:

**Pull request closed without merging**
