### PR TITLE
Update Xcode on CI to 2.5.1

### PR DESCRIPTION
**Pull request by BasThomas**
Followup from #2187 / [this comment](https://github.com/Moya/Moya/pull/2187#discussion_r699107095)

### CODE REVIEW

**Comment by BasThomas** [comment]
cc @OhKanghoon

**Comment by OhKanghoon** [comment]
If you upload the Xcode version, you need to change the iOS and tvOS versions to 14.5 in the Rakefile..

**Review by OhKanghoon — COMMENTED** [review]
Oops!
tvOS name should be changed to`Apple TV 4K (at 1080p) (2nd generation)`

**Comment by BasThomas** [comment]
Sure bot, but what happened that made you fail?

**Review by OhKanghoon — APPROVED** [review]

**Comment by AndrewSB** [comment]
might be relevant: https://github.com/dbgrandi/danger-prose/issues/32

**Comment by BasThomas** [comment]
Merging for now then.

**Pull request merged**
