### PR TITLE
[WIP] Swift 2.0

### LINKED ISSUE #156: Swift 2.0 branch?
I want to integrate Moya into an Xcode 7/Swift 2.0 project. Any chance of an official branch to support this to go along with the Alamofire swift-2.0 branch?

### PR DESCRIPTION
**Pull request by esttorhe**
# Fix #156 

New `PR` with the fixes from @ashfurrow after the transition to an organization (Old was #162 )

## Done:
- Currently using Quick and Nimble `swift-2.0` branches
- `AlamoFire` `swift-2.0` branch as well
- Moya Core is compiling
- Minimal Swift 2.0 migration (not reworked; only made it compile)
- @garethknowles migrated the code for `RxSwift`

## TODO:
- [ ] Migrate `ReactiveCocoa` to `swift2` branch
  - [ ] Generate a `podspec` for `swift2` branch first

### CODE REVIEW

**Comment by esttorhe** [comment]
Worth noting that this branch is currently not compiling on my computer with the following message:
```console
Module file was created by an older version of the compiler; rebuild 'Security' and try again: /Applications/Xcode-7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/Security.swiftmodule
```

**Comment by esttorhe** [comment]
After uninstalling and re installing `Xcode 7 ß5` the project is compiling with `Swift 2.0` now :sunglasses:

**Comment by ashfurrow** [comment]
Fantastic! Let me know when this is ready for review :tada:

**Comment by esttorhe** [comment]
Will do; just need to finish the `ReactiveCocoa` `podspec` and in theory that will make it compile 100%; next step would be to «translate» to `Swift 2.0` and take advantage of stuff like `guard` and/or `throws`, etc

**Comment by esttorhe** [comment]
@Moya/contributors given the new repo organization would it make more sense to close this `PR` (again) and start 3 different ones; 1 `Swift 2.0` for the core, and 2 for each Reactive extension repo? (maybe 3 because there's a shared reactive core) ?

**Comment by ashfurrow** [comment]
For now, why don't we PR against this one. I'd rather not make swift-2 support depend on getting Carthage builds working. Shouldn't be difficult to transition then.

**Comment by esttorhe** [comment]
@Moya/contributors I'm almost done with this **BUUUUT**

After creating a podspec for `ReactiveCocoa` https://github.com/esttorhe/ReactiveCocoa/blob/swift2/ReactiveCocoa.podspec and correctly configuring it i'm facing one last issue.

When building `ReactiveCocoa` scheme on `Demo.xcworkspace` everything works as expected; but if I try to build `Pods` or `Moya` I'm getting this error:

```console
/Users/<username>/Library/Developer/Xcode/DerivedData/Demo-dwrrownhydordrffokwamvlwfmga/Build/Products/Debug-iphonesimulator/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:94:9: 'ReactiveCocoa/ReactiveCocoa.h' file not found
```

And here's the generated file:
```objectivec
// Generated by Apple Swift version 2.0 (swiftlang-700.0.52.2 clang-700.0.65)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import Foundation.NSURLSession;
#endif

#import <ReactiveCocoa/ReactiveCocoa.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"


/// Wraps an Action for use by a GUI control (such as NSControl or UIControl), with KVO, or with Cocoa Bindings.
SWIFT_CLASS("_TtC13ReactiveCocoa11CocoaAction")
@interface CocoaAction : NSObject

/// The selector that a caller should invoke upon a CocoaAction in order to execute it.
+ (SEL __null_unspecified)selector;

/// Whether the action is enabled.
///
/// This property will only change on the main thread, and will generate a
/// KVO notification for every change.
@property (nonatomic, readonly) BOOL enabled;

/// Whether the action is executing.
///
/// This property will only change on the main thread, and will generate a
/// KVO notification for every change.
@property (nonatomic, readonly) BOOL executing;

/// Attempts to execute the underlying action with the given input, subject to the behavior described by the initializer that was used.
- (IBAction)execute:(id __nullable)input;
+ (BOOL)automaticallyNotifiesObserversForKey:(NSString * __nonnull)key;
@end



/// Wraps a dynamic property, or one defined in Objective-C, using Key-Value Coding and Key-Value Observing.
///
/// Use this class only as a last resort! <code>MutableProperty
/// </code> is generally better
/// unless KVC/KVO is required by the API you're using (for example,
/// <code>NSOperation
/// </code>).
SWIFT_CLASS("_TtC13ReactiveCocoa15DynamicProperty")
@interface DynamicProperty : RACDynamicPropertySuperclass

/// The current value of the property, as read and written using Key-Value Coding.
@property (nonatomic, getter=rac_value, setter=setRac_value:) id __nullable value;

/// Initializes a property that will observe and set the given key path of the given object. object must support weak references!
- (nonnull instancetype)initWithObject:(NSObject * __nullable)object keyPath:(NSString * __nonnull)keyPath OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSNotificationCenter (SWIFT_EXTENSION(ReactiveCocoa))
@end


@interface NSURLSession (SWIFT_EXTENSION(ReactiveCocoa))
@end


@interface RACCommand (SWIFT_EXTENSION(ReactiveCocoa))
@end


@interface RACDisposable (SWIFT_EXTENSION(ReactiveCocoa))
@end

@class NSDate;

@interface RACScheduler (SWIFT_EXTENSION(ReactiveCocoa))
@property (nonatomic, readonly) NSDate * __nonnull currentDate;
@end


@interface RACSignal (SWIFT_EXTENSION(ReactiveCocoa))
@end

#pragma clang diagnostic pop
```

The faulting line being 94:
```objectivec
#import <ReactiveCocoa/ReactiveCocoa.h>
```

Any ideas why it works when building it separately works but not when trying to build `Pods` or `Moya` ?

**Comment by ashfurrow** [comment]
Whoa! Esteban, how did you make the RAC 3 podspec? I could update the existing one on CocoaPods trunk if that would help.

**Comment by esttorhe** [comment]
@ashfurrow I forked `ReactiveCocoa` and then added the `.podspec` to the `swift2` branch.

Even created a custom `tag` just to test it but sadly I can't make it work inside the `Pods` project.


If you can update the `podspec` I would give it a try with your version

**Comment by ashfurrow** [comment]
I'll see what I can do.

**Comment by ashfurrow** [comment]
@esttorhe It looks like RAC 3 beta 9, as well as a newer release candidate, are both on CocoaPods Trunk: https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/3.0-beta.9/ReactiveCocoa.podspec.json

So you should be able to use them.

**Comment by esttorhe** [comment]
Wouldn't that fail if I try to use that `podspec` but pointing to `swift2` branch?

**Comment by ashfurrow** [comment]
AHHH, right >.<

I don't see anything official from ReactiveCocoa about Swift 2 – normally, I'd just point it at a branch of theirs in the Podfile. They _have_ a `swift2` branch, but I dunno if that'll work.

**Comment by ashfurrow** [comment]
@esttorhe could you create a new PR to Moya's `swift-2.0` branch? We can merge it then.

**Comment by esttorhe** [comment]
@ashfurrow :scream: dear lord; this was pointing to `master` !?

hopefully third time is the charm :sparkles: 

I'll create the `PR` right now and will close this one.

**Pull request closed without merging**
