### PR TITLE
Merge master into 9.0.0 dev

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by pedrovereza** [comment]
Not sure if it was intentional, but 23be21483154bfed6b2a851cee8c6eb0ea66212f merged branch `9.0.0-dev` into `master`. If that's correct, we can delete branch `9.0.0-dev` 🤔

**Comment by BasThomas** [comment]
Wow, that was a conflict GitHub wanted to resolve on this PR. Didn't mean to do that... 😔

**Comment by pedrovereza** [comment]
@BasThomas No worries, #1015 should undo it :wink:

**Comment by pedrovereza** [comment]
Ok, the changes from #993 are already in `master` but reverted in #1015, that's why the git won't try to apply #993 again. I think we have to merge this as-is an reapply 249e436ab1c32f212a195afbe411fe5234aba81f on `9.0.0-dev`

**Pull request merged**
