### PR TITLE
Includes GitHub Releases along with git tags

### PR DESCRIPTION
**Pull request by ashfurrow**
Basically, GitHub has its own idea of git tags called "Releases", and Carthage uses _releases_ instead of _tags_ when you specify GitHub.

So the following two lines in a Cartfile are _not_ necessarily equivalent.

```
github "Moya/Moya"
git "https://github.com/Moya/Moya.git"
```

By added a GitHub Release, we avoid confusion with people installing older versions of Moya by accident. I've automated this to make sure I don't forget.

See https://github.com/Moya/Moya/issues/335 & https://github.com/Moya/Moya/issues/332

### CODE REVIEW

**Comment by ashfurrow** [comment]
@mpurland When you get a moment, could you review this PR?

**Comment by orta** [comment]
:+1:

**Comment by mpurland** [comment]
@ashfurrow Okay, sure, let me have a look

**Comment by petester42** [comment]
Want to hit that merge button @mpurland?

**Comment by mpurland** [comment]
:boat:

**Pull request merged**
