### PR TITLE
Test Cleanup

### LINKED ISSUE #271: Investigate extraneous podspecs
Continuing conversation started in https://github.com/Moya/Moya/pull/267

- Do we need the extra podspecs? 
- If so, why? Document that somewhere.
- If we don't need them, let's get rid of 'em! We can vastly simplify unit tests this way.

### PR DESCRIPTION
**Pull request by ashfurrow**
Deduplicates types that were previously defined in extraneous podspecs. We had duplicated them before because of our library structure, which was fixed in #267. This PR puts the separate copies back in one place. 

Fixes #271.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Continuous integration passes, and this PR only affects unit tests. Should be a good one for someone to review if they've never merged a PR before /cc @Moya/contributors

**Comment by JRHeaton** [comment]
Nice! Always feels good to drop duplicate code. I'm not sure the protocol for PRs is here but I've reviewed the raw diff and everything looks good to me :+1:

**Comment by ashfurrow** [comment]
@JRHeaton awesome! Wanna hit the "merge" button?

**Comment by ashfurrow** [comment]
:tada: thanks!

**Comment by alcarvalho** [comment]
Best gif ever for merging a PR! :grin:

**Pull request merged**
