### PR TITLE
Add manual installation guide

### LINKED ISSUE #780: Manual install instructions?
Any chance for instructions on how to add Moya to a project manually? I would love the fully spelled out idiot/newbie version if you don't mind? 

Thanks in advance.

### PR DESCRIPTION
**Pull request by BasThomas**
Hmm, how should we do this? Alamofire has a great explanation on how to add their project as a `git submodule`, which are roughly the same steps needed for `Result` and `Moya`.

I don't think I've captured that the best I could; I'd love some feedback on how to make it better!

Fixes #780

### CODE REVIEW

**Comment by BasThomas** [comment]
@jaymutzafi: please check if this works for you, and let me know if you have any questions / improvements!

**Comment by AndrewSB** [comment]
`Do the same for Moya` is a little sparse, what if we tried to copy more of Alamofire's docs?

almost exactly all of this, tweaked to work for Moya
screen shot 2016-12-08 at 2 23 18 pm

**Comment by BasThomas** [comment]
Was considering that. And then make it "compatible" with all three frameworks?

**Comment by AndrewSB** [comment]
@BasThomas that sounds good to me!

**Comment by BasThomas** [comment]
Updated them. If someone could try this and provide feedback, that'd be awesome!

**Comment by jaymutzafi** [comment]
Awesome!

**Pull request merged**
