### PR TITLE
update RxMoyaProvider.request to return a Single

### PR DESCRIPTION
**Pull request by AndrewSB**
Implements #1011, and changes the signature of RxMoyaProvider.request to return a `Single<Response>` instead of an `Observable<Response>`.

cc/ @andreyfel @damienrambout: would love both of you to sign off on this before it's merged in

### CODE REVIEW

**Comment by BasThomas** [comment]
This is breaking and should go in `9.0.0` and not master, right?

**Comment by BasThomas** [comment]
Also, some Cocoapods package versions don't match up with Cartfile anymore.

**Comment by andreyfel** [comment]
I think it would be better to create new Provider, like RxSingleMoyaProvider to make this change non-breaking. In this way we will support both Observable and Single. And it will be easier to migrate to the Single.

**Comment by AndrewSB** [comment]
@BasThomas: In its current state, it is breaking. @BasThomas can you match the Cocoapods package versions that I missed?

@andreyfel: I don't know if adding another choice to a very simple module is a smart idea long-term. I feel as though we should either stick with Observable and not make this change, or embrace RxSwift's new semantics and publish Single. But not try to inelegantly solve both
After understanding the change, the easy path to migrate to the new RxMoya syntax will simply be for a consumer to extend `RxMoyaProvider` and supply a method that returns an `Observable<Response>`, which `.asObservable()`'s the new `RxMoyaProvider.request`

**Comment by gperdomor** [comment]
This PR revert the changes introduced in #993... This can't be merge yet

**Comment by pedrovereza** [comment]
I think we should first deal with #1013 (which is also reverting #993)

**Comment by gperdomor** [comment]
@AndrewSB please rebase

**Comment by pedrovereza** [comment]
@AndrewSB can you rebase against `9.0.0-dev` and reapply your changes? (See #1017) :wink:

**Comment by AndrewSB** [comment]
All rebased! cc/ @gperdomor can you approve?

I need to fix a couple tests to get CI passing, working on them soon 😄

**Comment by gperdomor** [comment]
#993 is still reverted in this PR

**Comment by pedrovereza** [comment]
@gperdomor @AndrewSB Hey, I fixed the branch by cherry-picking all changes on top of `9.0.0-dev`: https://github.com/Moya/Moya/commits/observable-single-9.0

We can:

1 - Open a new PR from that branch
2 - Push force to `observable-single`, meaning everyone will have to delete the branch locally and fetch again (but we keep this PR)

I'm ok either way 😄

**Comment by gperdomor** [comment]
Option 1 is more cleaner i guess

**Comment by justinmakaila** [comment]
I'm not a user of RxSwift, but just cruising through their API (you know, trying to form an educated opinion), it looks like `Single<MoyaResponse>` IS the most analogous structure to represent a network request, unless the request is repeating, in which case, `Observable` would make sense. In the case of a repeating request however, it should be on the developer to format their signal in that way.

Realistically, I don't think we should not embrace this change just because our API already utilizes `Observable`, but rather note it as a breaking change and release.

Forcing people to make changes to existing code bases to implement the best practices from one of our dependencies for a new version should be expected, and as @AndrewSB mentioned, you can just add `asObservable()` if you're a client who wants to continue to use `Observable`.

**Comment by AndrewSB** [comment]
Thank you for sharing your thoughts @justinmakaila!

@pedrovereza: I'm lazy, and I don't see the harm in #2, but feel free to go ahead with whichever one makes you more comfortable

**Comment by pedrovereza** [comment]
@BasThomas @AndrewSB @gperdomor @justinmakaila @andreyfel 
Hey I created #1020 to avoid more branch issues. Please continue the discussion in that PR and use branch `observable-single-9.0` for new additions. I'll delete `observable-single`to avoid confusions :wink:

**Comment by AndrewSB** [comment]
Thanks Pedro 😊

**Pull request closed without merging**
