### PR TITLE
Bump RxSwift version to 6

### PR DESCRIPTION
**Pull request by uypanha**

### CODE REVIEW

**Comment by rohita-personatech** [comment]
Can we get this PR merged?

**Comment by haithngn** [comment]
@uypanha you forgot to update Cartfile

**Comment by jordizspmobile** [comment]
How can I support this?

**Review by uypanha — COMMENTED** [review]
Updated Cartfile of Reactive/RxSwift version to 6

**Comment by uypanha** [comment]
@haithngn I've updated and request with new PR.

**Comment by onsissond** [comment]
What about this PR? Is it live?

**Comment by BasThomas** [comment]
Thank you, @uypanha, and others for chiming in! RxSwift seems to have been updated to 6.0 via #2120; I'm going to close this one. We'll look into releasing a new version of Moya soon, so you can use a tagged release with RxSwift 6.0!

Thanks again for your contributions!

**Pull request closed without merging**
