### PR TITLE
Add MultiTarget sample

### LINKED ISSUE #1259: Update MultiTarget example to have working code.
Related #1150. Basically we've got some code that is not working or is lacking some pieces. I've recreated some of the code already so it can be used as a starting point:

```swift
protocol TestResultType {
    associatedtype T
    static func parse(_ object: Any) -> Self?
}

protocol DecodableTargetType: Moya.TargetType {
    associatedtype ResultType: TestResultType
}

final class MultiMoyaProvider: MoyaProvider<MultiTarget> {
    
    typealias Target = MultiTarget
    
    override init(endpointClosure: @escaping EndpointClosure = MoyaProvider.defaultEndpointMapping,
                  requestClosure: @escaping RequestClosure = MoyaProvider.defaultRequestMapping,
                  stubClosure: @escaping StubClosure = MoyaProvider.neverStub,
                  manager: Manager = MoyaProvider<Target>.defaultAlamofireManager(),
                  plugins: [PluginType] = [],
                  trackInflights: Bool = false) {
        super.init(endpointClosure: endpointClosure, requestClosure: requestClosure, stubClosure: stubClosure, manager: manager, plugins: plugins, trackInflights: trackInflights)
    }
    
    func requestDecoded<T: DecodableTargetType>(_ target: T, completion: @escaping (_ result: Result<T.ResultType, Moya.Error>) -> ()) -> Cancellable {
        return request(MultiTarget(target)) { result in
            switch result {
            case .success(let response):
                if let parsed = T.ResultType.parse(try! response.mapJSON()) {
                    completion(.success(parsed))
                } else {
                    completion(.failure(.jsonMapping(response)))
                }
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by AYastrebov**
Add MultiTarget sample

Fixes #1259

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @AYastrebov. Thanks for the PR! However, we were thinking rather about improving our documentation [here](https://github.com/Moya/Moya/blob/master/docs/Examples/MultiTarget.md). We don't really have an implementation of `MultiTargetProvider` in there and that's what we were trying to fix.

The PR is really good in the matter of updating the example, but we'll still need to update the documentation as well. Would you be up for doing it? 😉

**Comment by AYastrebov** [comment]
@sunshinejr ok, I'll do it this week

**Comment by sunshinejr** [comment]
Sure, thanks for doing this! You'll need to rebase as few PRs were merged in the meantime.

**Comment by sunshinejr** [comment]
Sure, thanks for doing this, @AYastrebov! You'll need to rebase as few PRs were merged in the meantime.

**Comment by sunshinejr** [comment]
@AYastrebov I'm sorry but I'm gonna close this one due to inactivity. Once you have some more free time, please create a new PR with the changes mentioned. Thank you again for your time!

**Pull request closed without merging**
