### PR TITLE
[SPM] Git suffix + .gitignore

### PR DESCRIPTION
**Pull request by sunshinejr**
In this PR:

1. Add .git suffixes. Rationale: [Stencil#84](https://github.com/kylef/Stencil/pull/84) and [Stencil#101](https://github.com/kylef/Stencil/issues/101). Basically really similar situation in our case. `ReactiveSwift` has `Result` as a dependency with `.git` suffix in `Package.swift`, and we also have `Result` dependency - but without `.git` in `Package.swift`. It might also resolve our problem in [SPM-compat](https://github.com/apple/swift-source-compat-suite/pull/35).
2. Add `Package.pins` to `.gitignore`, as per [SPM docs](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#automatic-pinning).

### CODE REVIEW

**Comment by BasThomas** [comment]
Nice! Could this also fix #1072 / https://github.com/apple/swift-source-compat-suite/pull/35? Seems like this might have been the issue there.

**Comment by sunshinejr** [comment]
It _might_, we will have to test it once this is merged.

**Comment by BasThomas** [comment]
Should we also add the git suffix to the Readme SPM instructions for Moya itself?

**Comment by BasThomas** [comment]
Other than that, this LGTM.

**Comment by sunshinejr** [comment]
Oh, right! Thanks, I'm on it. 👍

**Comment by sunshinejr** [comment]
Done 👍

**Pull request merged**
