### PR TITLE
[WIP] Improve DangerFile to warn for podspec, Cartifle or SPM changes

### LINKED ISSUE #1534: Add rules for DangerFile about Package.Swift and Package.Resolved
Hi,

Current `DangerFile` will warn if we don't update `podspec` and `cartfile` (+resolved) at the same time. Which is good. 

I think we should add the same rule for `Package.Swift` and `Package.resolved`.

For the dependencies we are using
- podspec
- Cartfile
- Cartfile.resolved
- Package.Swift
- Package.Resolved

`Danger` should warn if one of those file is modified but the commit does not contains all the files listed above.

This is to prevent the issue that we had for https://github.com/Moya/Moya/pull/1470 were everything was updated except `Package.Resolved`.

However I think we can make the message clearer. for example
`Cartfile has been updated but not Cartfile.resolved did you forgot to run carthage update`

I'm not 100% familiar with Danger but I can try to make a PR.

### PR DESCRIPTION
**Pull request by lucas34**
**Work in progress**: fixes #1534

Attempt to improve DangerFile when updating dependencies files.

####  Will warn for resolved files:
- Updating `Cartfile` but NOT `Cartfile.resolved`
- Updating `Package.Swift` but NOT `Package.resolved `
- Updating `Cartfile.resolved` and NOT `Package.resolved` (and vice versa)

#### Will warn for `podspec`, `Cartfile` or `Package.Swift`
- Updating `podspec` but NOT `Cartfile` or `Package.Swift`
- Updating `Cartfile` but NOT `podspec` or `Package.Swift`
- Updating `Package.Swift` but NOT `podspec` or `Cartfile`

#### Will NOT warn anymore:
- Updating `Cartfile.resolved` and `Package.resolved` without any other file
This is a breaking changes compare to the previous behaviour. 
This is to prevent false positive in this kind of PR https://github.com/Moya/Moya/pull/1532

### Example:
If I update only `podspec` and `Cartfile` I should have this two warnings:
- The `podspec` was updated, but there were no changes in either the `Cartfile` nor `Package.swift`. Did you forget updating `Cartfile` or `Package.swift`?
- The `Cartfile` has been updated but not the `Cartfile.resolved`. Did you forgot to run `carthage update` ?

In order to solve the first warn I will need to update Package.swift. I will then have
- The `Package.swift` has been updated but not the `Package.resolved`. Did you forgot to run `swift package update` ?

So all files should be covered.

Please give me your feedback. Missing case (?).
I **haven't test yet**, I'm having issue to run `danger` locally

### CODE REVIEW

**Comment by BasThomas** [comment]
Looks awesome! Although this is super confusing, it seems like it will improve things.

What about another PR targeting this branch so we can test all scenarios there? Then you also don't have to run Danger locally, and we can all see the results. :)

**Comment by lucas34** [comment]
The branch is on my local fork so I cannot make a PR with this branch as target. It will create locally on mine.
So the best I can do is, I create a branch on Moya repo with the changes above. Then since it's on the main Moya repo we can easily create PR for the different use cases.

**Comment by BasThomas** [comment]
Ah - yes. And you're right, as a member you can clone the Moya repo and create a branch here 👍

**Comment by lucas34** [comment]
I pushed in Moya with a new branch `enhancement/dangerfile` 
https://github.com/Moya/Moya/tree/enhancement/dangerfile

And I created a PR from my repo to Moya to test https://github.com/Moya/Moya/pull/1537

Closing this PR now. we can merge from `enhancement/dangerfile` directly

**Pull request closed without merging**
