### PR TITLE
Bump dependencies for Result and ReactiveSwift

### LINKED ISSUE #1657: Update dependency: Result 3.2.4 -> 4.0.0
Moya 11.0.2
CocoaPods

### PR DESCRIPTION
**Pull request by sunshinejr**
Fixes #1657.

**Edit:** This was a live contribution on the Wro Open Source conference, now I see that I forgot about updating the lockfiles, will do that later on :D

### CODE REVIEW

**Comment by sunshinejr** [comment]
Okay, updated the lockfiles but there is a thing - ReactiveSwift will have a release in a few as there is already 4.0.0-rc.1 so we should watch for the update and probably release a major version as well.
cc @SD10

**Comment by SD10** [comment]
@sunshinejr I agree we need to make a major release soon. I was pretty much waiting on ReactiveSwift because I thought it was the cause of the CI failures. I don't have time to dig on that one.

I would have time to do stuff related to documentation for the release -- migration guide, making the release, etc.

**Comment by SD10** [comment]
ReactiveSwift is on 4.0.0-rc.2 now for 20 days 😐

**Comment by sunshinejr** [comment]
@SD10 Yeah I was thinking about the beta version with their RC but was thinking that they would probably release a major in a day or two so didn't bother.

**Comment by xaverlohmueller** [comment]
Will this release with 12.0? Sooner maybe?

**Comment by SD10** [comment]
@xaverlohmueller It will release with 12.0

**Comment by larryonoff** [comment]
please bump ReactiveSwift to 4.0 release in this PR

**Comment by freak4pc** [comment]
@sunshinejr Noticed 4.0.0 was released so helped out a bit. Feel free to take it from here :]

**Comment by sunshinejr** [comment]
Aw, thanks @freak4pc for syncing the PR and thanks to all for taking time to review it! 🧡 

I also updated `.podspec` so it is in sync with newest `ReactiveSwift` version; please do a final check if you can!

**Pull request merged**
