### PR TITLE
[WIP] Move Tests/ to root dir (so we can use `swift test` when we're swift package manager compatible)

### PR DESCRIPTION
**Pull request by AndrewSB**
Related to #696 

Currently there's no watchOS test target. Was that an oversight? Should I create one?

### CODE REVIEW

**Comment by petester42** [comment]
You can't. It doesn't exist.

**Comment by AndrewSB** [comment]
Oh wow 😂😂
I wonder when Apple will decide that watch apps deserve tests ;p

**Comment by AndrewSB** [comment]
This works with a carthage install, but is completely broken when you're using Cocoapods, and since CI uses Cocoapods as well, CI seems to be broken.

Can anyone from @Moya/contributors who's familiar with Cocoapods update the tests to not break when installing through `pod`?

**Comment by BasThomas** [comment]
Might take a look at this soon. :)

**Comment by AndrewSB** [comment]
Sounds awesome @BasThomas!

I tried rebasing, but I'm not sure what a lot of the changes on `master` have been.
Wasn't sure how to handle this conflict while rebasing

screen shot 2016-12-01 at 12 29 58 pm

So I didn't finish the updating this branch. Do you know why those files were changed on master? 
I'm around to fix the conflicts, or you can take a shot if you'd like

**Comment by BasThomas** [comment]
Hmm, just started "fresh" on this, but Xcode is complaining when moving the `Tests` directory into the root.

screen shot 2016-12-09 at 19 44 35
screen shot 2016-12-09 at 19 44 40
screen shot 2016-12-09 at 19 44 47

Not sure how to proceed :/

**Comment by AndrewSB** [comment]
fresh as in pulling from `master` and manually redoing the work? If that's what you're thinking of doing, I can take the lead instead. I got it working before, so I can probably figure it out again.

Xcode looks as if it's expecting some source files and they're no longer there. Maybe you moved them in the filesystem without updating the xcodeproj?

**Comment by AndrewSB** [comment]
@BasThomas I think I'm just going to redo this PR, that seems easier than managing all the rebase merge conflicts we're going to hit.
I'll do it later today

**Comment by BasThomas** [comment]
👍

**Comment by AndrewSB** [comment]
Created #885 to continue this

**Pull request closed without merging**
