### PR TITLE
@orta => Swift 2.0 master merge

### PR DESCRIPTION
**Pull request by ashfurrow**
Merging current `master` into `swift-2.0` – this is the PR that we'll review any issues with the changes to accommodate Swift 2. After its merged, we'll be immediately merging into master and pushing a new release on CocoaPods. 

After that, we'll be concentrating on finalizing Carthage support thanks to @justinmakaila's hard work and helpful advice from @gfontenot. _Then_ we can get to those fun [short term issues](https://github.com/Moya/Moya/labels/short%20term) :heart_eyes_cat: 

Awww yisssss short term issues

/cc @Moya/contributors

### CODE REVIEW

**Comment by ashfurrow** [comment]
Looks like a failing intermittent test. I'll investigate.

**Comment by ashfurrow** [comment]
OK, I believe I've fixed the test. The test was checking to make sure that a cancelled request sent an error. The failure seems to be caused by OHHTTPStubs sometimes stubbing the response before it had a chance to be cancelled. I've added a half second delay to all stubbed responses.

**Comment by orta** [comment]
Reviewed in Person - :+1:

**Comment by ashfurrow** [comment]
Slight delay in the CocoaPods release – you can use the `master` branch in your Podfile for now.

**Pull request merged**
