### PR TITLE
[WIP][CI] Add new script to exit on non-trivial changes (docs, markdown, etc)

### PR DESCRIPTION
**Pull request by Sherlouk**
Working towards #1286, created a new script which lists the file names of anything changed within the provided commit.

As per CircleCI's docs (https://circleci.com/docs/1.0/environment-variables/) I've gotten the "CIRCLE_SHA1" variable which should be the commit hash.

Following that I do an inverted grep which searches for an entry that doesn't match the regex (so source file changes etc), and in that occasion will exit with code 0 (success).

In the event it does find something, it'll return with exit code 1 which I'm hoping is enough for Circle to stop on.

For testing purposes I've added some prints to see what's happening, the regex isn't final as will need to find out what we want to search for and include/exclude!

Creating a quick WIP pull request just so I can get CircleCI to give this a run. (Wasn't letting my build on my fork 🤷‍♂️ )

### CODE REVIEW

**Comment by sunshinejr** [comment]
@Sherlouk I've labeled it with `[WIP]` - please remove it once it is ready for review 😉

**Comment by Sherlouk** [comment]
Sorry yea I'm just staring blankly trying to work out whether Circle is just being slow to spin up, or I've done something wrong 🤔 

More likely the latter, but I don't know 😂

**Comment by marcomorain** [comment]
@Sherlouk @sunshinejr you can put the string `[ci skip]` into the commit message to skip CI builds - does that do what you need?

**Comment by sunshinejr** [comment]
@marcomorain That's correct, but new contributors might not know the rule and we are trying to automate the process without additional steps if possible.

**Comment by Sherlouk** [comment]
Pushing a new commit was enough to get Circle running again, couple stupid mistakes later (shebang and file permissions) it's managed to get past that stage.

Next steps is to make sure I can stop a build from continuing but with a successful code!

**Comment by Sherlouk** [comment]
@sunshinejr So noticing two things immediately, due to the way CircleCI separate everything into isolate stages it makes it pretty difficult to exit early with a success flag (obviously you can drop a failure at any point in time).

The other thing is that Circle don't provide an easy way to get a range of commits, only the current commit. This in theory works for things like this pull request where it's running every commit, but in the instance where a user pushed up `x` commits and then creates a pull request where they only update a doc - it would only check the changes on the latest commit.

The second point is easier to fix with a few extra commands in order to work out the range of commits based on the branch, and diffing against master rather than solely on a given commit. Though honestly I'm not sure how to deal with the first one.

Obviously failing is an easy solution, but that would be a royal pain in the ~self censorship~ as you'd always have to find out why it failed. Another possible solution is to define a env variable "trivial_changes" and if that's found you just skip all the build stages (kind of messy, easy to make mistakes with future changes).

Maybe this wasn't the card to learn Circle with 😂 

Willing to take advice at this point?

**Comment by pedrovereza** [comment]
> due to the way CircleCI separate everything into isolate stages it makes it pretty difficult to exit early with a success flag (obviously you can drop a failure at any point in time).

@Sherlouk Have you checked `circleci step halt` ([here](https://discuss.circleci.com/t/stop-build-with-success-failure-at-any-point-in-the-build-life-cycle/2691/2))?

**Comment by Sherlouk** [comment]
@pedrovereza Yeah! I think I saw that exact post in fact, but unfortunately when I did it was saying that the command `circleci` did not exist!

See this build: https://circleci.com/gh/Moya/Moya/1898?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pedrovereza** [comment]
@Sherlouk Okay, maybe it's because we're not using [Circle 2.0](https://circleci.com/docs/2.0/migrating-from-1-2/#steps-to-configure-required-20-keys) yet 🤔

**Comment by sunshinejr** [comment]
@pedrovereza is probably right. If you want more info about CircleCI 2.0 with Moya see #1194. I have already made some progress and will try if skipping the job will be easier to do there.

**Comment by Sherlouk** [comment]
You may be right about the Circle 2.0 stuff! @sunshinejr if you wanna give it a go and just see if it works then great -- The script is fairly simple from that point.

Shall we close this PR and move discussion back to 1286 until we know the situation?

**Comment by sunshinejr** [comment]
Good idea @Sherlouk. Sorry for the trouble :( I'll make a PR with my WIP branch to see how it works!

**Pull request closed without merging**
