### PR TITLE
Update Moya.podspec

### PR DESCRIPTION
**Pull request by mustafaibrahim989**
Update RxSwift 2.1.0

### CODE REVIEW

**Comment by ashfurrow** [comment]
Great idea! Will wait for :green_apple: then merge and release.

**Comment by ashfurrow** [comment]
Hey there! Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by ashfurrow** [comment]
Fabo – this has been released as 6.1.1, thanks! :tada:

**Comment by mustafaibrahim989** [comment]
Thanks for letting me contribute in the amazing Moya :tada: . and I hope I can help :)

**Comment by ashfurrow** [comment]
I'm sure you will :bow: But no pressure to, we all have lives outside open source!

**Pull request merged**
