### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LarsJK**
Fixed headers

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @LarsJK! Thanks for the changes! 🎉 
These warning doesn't have anything to do with this PR so I'm gonna merge this anyways :)

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by LarsJK** [comment]
Thanks guys! Love how you run open source projects ❤️

**Comment by BasThomas** [comment]
Nice, thanks @LarsJK!

**Pull request merged**
