### PR TITLE
[WIP] [CI] Update to CircleCI 2.0

### LINKED ISSUE #1194: [CI] Support multiple Swift versions.
Right now #1193 will update our Swift support to Swift 3.1, 3.2 and 4.0. While it is awesome, we should do some checks to make sure we do not break these unintentionally. We can do builds for all of them, but I think checking for 3.2 & 4.0 compatibility should be enough. What do you guys think?

### PR DESCRIPTION
**Pull request by sunshinejr**
Note: This is still WIP (I'm gonna squash these commits afterwards as well :D)

To-do list:
- [x] Update to CircleCI 2.0 workflows
- [x] Add testing simultaneously for both Swift 3.2 & Swift 4.0 (Resolves #1194)
- [ ] Test for trivial changes (in progress, thanks to @Sherlouk)
- [ ] Build new examples
- [ ] Add SPM compatibility test
- [ ] Add CocoaPods compatibility test

### CODE REVIEW

**Comment by pedrovereza** [comment]
I'm a bit concerned on the amount of things this PR wants to achieve 😅 

@sunshinejr  Do you feel we could create an issue to keep track of all these steps and tackle each one in a sepparate PR? Or are you comfortable making all these changes at once?

**Comment by sunshinejr** [comment]
Aye, @pedrovereza, I’ll do that after I got it working, just need a playground that i can test, thus why WIP PR.

**Comment by AndrewSB** [comment]
screen shot 2017-10-11 at 3 25 33 pm

squashing sounds good to me, but its a little worrying that some of these commits are showing up in the log

**Comment by AndrewSB** [comment]
also, is there a reason why this isn't being targeted to master, but 10.0-dev instead?

**Comment by sunshinejr** [comment]
@AndrewSB basically right now it doesn't really matter, I use it as a playground to test everything (especially PRs), but you are right - we would do it in master and 10.0.0-dev both. About he commits - are showing as I didn't rebase to current 10.0.0 yet.

**Comment by AndrewSB** [comment]
I'm so confused. I don't remember closing this. Was this landed elsewhere?

**Comment by SD10** [comment]
@AndrewSB I think all open PRs targeting `10.0.0-dev` were closed upon deletion of the branch.

**Comment by BasThomas** [comment]
Ah, so that's why @AndrewSB closed a few things. I was confused 🙈. I'll reopen and point to master for now?

**Comment by AndrewSB** [comment]
I'm sorry about that! 10.0.0-dev was behind master, so I thought we were done with it!

**Comment by BasThomas** [comment]
No worries! :)

**Comment by BasThomas** [comment]
Also, I think it's kind of GitHub's fault for not letting you know that removing the branch would close some PRs :)

**Comment by AndrewSB** [comment]
😓

**Comment by sunshinejr** [comment]
Oh, no worries @AndrewSB, I did it once as well 😅 I agree that there should be a warning before deleting the branch that targets multiple PRs. Also I need to start working again on this one, been a long time.

**Comment by sunshinejr** [comment]
I'm gonna focus on this one as Xcode 9.2 is the last one supported on Circle 1.0. Gonna finish it and split into smaller parts if possible.

**Pull request closed without merging**
