### PR TITLE
Carthage dependencies update

### PR DESCRIPTION
**Pull request by mpdomas**
Fixed a typo in [Cartfile](https://github.com/Moya/Moya/blob/master/Cartfile);
Updated [Cartfile.resolved](https://github.com/Moya/Moya/blob/master/Cartfile.resolved) after doing a local `carthage update`;

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hey there! Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by mpdomas** [comment]
Not sure why, but Carthage still checks out older version of Moya. `/Carthage/Checkouts/Moya/Cartfile` is as [was before merge](https://github.com/Moya/Moya/blob/e80519dfc31582f78459ffe7a754440bb9beb79e/Cartfile).
Cartfile contents:
```
github "Moya/Moya"
```
Any clues? Is there some sort of cache? Are there any other places that need to be changed (like semantic version)?
Can't find anything at [their issues](https://github.com/Carthage/Carthage/issues?utf8=✓&q=is%3Aissue+old).

**Comment by ashfurrow** [comment]
Ahh, we probably need to publish a new release that includes the changes. Will do shortly.

**Comment by mpdomas** [comment]
:tada:

**Comment by ashfurrow** [comment]
Cool, this has been released under [6.2.0](https://github.com/Moya/Moya/blob/master/Changelog.md#620). Let me know if that works :+1:

**Comment by mpdomas** [comment]
Like a charm :+1:

**Pull request merged**
