### PR TITLE
require extension-safe api for RxMoya and ReactiveMoya

### PR DESCRIPTION
**Pull request by spookyvision**
augmenting #1416 to include ReactiveMoya target as well

### CODE REVIEW

**Comment by sunshinejr** [comment]
Yup, can you add a `Changelog` entry for this one, @spookyvision? Other than that it looks great. 

About the Changelog update - you should rebase master before you add this one, as we already have one fix in it. This entry should be under `Fixed` column, as we enabled this flag before, but not for each target for both debug and release.

**Comment by spookyvision** [comment]
First time doing this, hope I did things right :)

**Comment by AndrewSB** [comment]
@spookyvision it's a little worrying to see 25 commits in this PR. Any idea why your PR is pulling in so many other commits?

**Comment by spookyvision** [comment]
@AndrewSB I rebased onto master as requested by @sunshinejr - my commits are actually far less. Should I start from scratch and cherrypick them?

**Comment by SD10** [comment]
I just did a roundtrip swap on the target branch of this PR and it seemed to remove a lot of the excess commits in this PR. I don't know if we want to squash the commits further but the changes LGTM

**Comment by sunshinejr** [comment]
I've resolved conflicts, it seems ready to merge! Thanks @spookyvision! 🎉

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Pull request merged**
