### PR TITLE
Added Gloss extension! 

### PR DESCRIPTION
**Pull request by spxrogers**

### CODE REVIEW

**Comment by colinta** [comment]
Nice!  Thanks for adding this to the README.  I took a quick glance at your adapter, and it looks very straightforward.  I think this is good to merge (and will, if no one else objects or beats me to it).

**Comment by sunshinejr** [comment]
Yeah, looks good! Thanks! 🎉

**Comment by spxrogers** [comment]
:tada: :smile:

**Comment by ashfurrow** [comment]
Hey there! Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by spxrogers** [comment]
awesome! sounds good, thanks for the invite @ashfurrow :grin:

**Pull request merged**
