### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by larryonoff**
* update ReactiveSwift to 2.0
* update RxSwift to 3.6.1

### CODE REVIEW

**Comment by larryonoff** [comment]
They only thing that worries me that some people won't be able to migrate to ReactiveSwift 2.0 quickly since there're some breaking changes, so as the new Moya.

**Comment by BasThomas** [comment]
Can you update the Demo's Podfile.lock as well? Just run `pod update` in the `Demo` directory.

**Comment by larryonoff** [comment]
@BasThomas done

**Comment by BasThomas** [comment]
Awesome, thanks @larryonoff! :)

**Comment by sunshinejr** [comment]
Good job, @larryonoff! However, we might want to wait with this one after the #1181 merge, since there are multiple changes to reactive providers.

**Comment by larryonoff** [comment]
@sunshinejr should I rebase my branch to `9.0.0-alpha.1` ?

**Comment by sunshinejr** [comment]
If you could it would be awesome 👍

**Comment by larryonoff** [comment]
@sunshinejr rebased.

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by larryonoff** [comment]
@ashfurrow thank you!

**Pull request merged**
