### PR TITLE
Feature/multipart upload multipartuploadable

### PR DESCRIPTION
**Pull request by justinmakaila**
This builds off of `feature/multipart-upload` a little bit, but makes it a bit more flexible. I think this one is better suited for production.

It better introduces the concept of an upload, rather than just the ability to perform multipart uploads.

This was heavily influenced by the chatter on #114, @guidohendriks and @startupthekid

### CODE REVIEW

**Comment by justinmakaila** [comment]
This still requires some tests for the other upload types, but multipart is working :+1:

**Comment by GuidoHendriks** [comment]
Looks really good, nicely done! 😎 Will have a good look at this soon, if only I had time I would have given it a shot myself.

**Comment by justinmakaila** [comment]
@GuidoHendriks There's still time, I'm sure there are bugs I'm missing cause I've been looking at it a bit too long

**Comment by justinmakaila** [comment]
Turns out that this builds on Carthage, unlike the last one. You have to run `carthage update --no-use-binaries`, because most of the distributed binaries were built with the old compiler /facepalm

**Comment by petester42** [comment]
Ya. I find that it is always better to set that on

**Comment by aschuch** [comment]
This looks really good to me. I think we should also consider adding a way to get progress information for uploads. Do you think an optional closure on the `request` method would be ok?

**Comment by justinmakaila** [comment]
@aschuch I'm down with that. I think it'd be coolest if we could get it like this:
```swift
let target = API.Target.SomeUploadTarget
APIProvider.request(target)
  .progress { bytesSent, totalBytes in
    let percentage = bytesSent / totalBytes
    self.progressView.value = percentage
  }
```
But that would require some contextual knowledge of the target (mostly that it's an upload).

**Comment by startupthekid** [comment]
I might be off base here but what about for multipart uploads, we create a `Response` subclass that has a progress method? That way all the normal methods on `Response` would work and for multipart, you'd get the progress you need.

Something like:

```swift
func request(token: Target) -> SignalProducer<UploadResponse, Error> {}
```

**Comment by justinmakaila** [comment]
@startupthekid I think you're on to something. Do @Moya/contributors see any issues with potentially introducing a new `Response` type?

**Comment by colinta** [comment]
I also like this implementation!  Feels very "Moya-esque" :smile: 

The "Response-subclass w/ `progress` method is a good idea to me, too.

Thanks for tackling this one!

**Comment by startupthekid** [comment]
That does mean though that `Response` can't be a `final` class. That should be ok though, makes Moya more extensible, especially if someone wants to provide a custom response class for debugging purposes or what have you.

Another interesting direction could be making a `ResponseType` protocol that `Response` provides the implementation for and then an `UploadResponseType` that conforms to `ResponseType` and adds a few handy progress methods. 

```swift
public protocol ResponseType: CustomDebugStringConvertible, Equatable {
    var statusCode: Int { get }
    var data: NSData { get }
    var response: NSURLResponse?

   ....
}

public protocol UploadResponseType: ResponseType {
    func progress(...)
}
```

**Comment by justinmakaila** [comment]
+1 to the `ResponseType` protocol.

Not sure how to integrate the progress though, because the response type wouldn't be available until after the request completes.

**Comment by startupthekid** [comment]
Instead of on `Response` it could be on `Request` and then `request` could send an intermediary request object that informs progress. Not sure how to go about implementing that though.

**Comment by justinmakaila** [comment]
We may have to introduce an `UploadRequest` or something along those lines... I'm imagining we'd just  add a `.progress { ... }` closure to the `Alamofire` call site which invokes the `progress` provided by `Moya`.

**Comment by jasl** [comment]
Or we may add `progress` [here](https://github.com/Moya/Moya/blob/master/Source/Plugin.swift#L19) and add a closure named `willPerformRequest(request: RequestType)` and call it before the request is sending out (for upload, we call it in `encodingCompletion`

**Comment by jasl** [comment]
But I think a better solution needs a breaking change, the `ParameterEncoding` is conflict with multipart-form-data, actually multipart-form-data is a kind of parameter's encoding, but Moya currently using Alamofire's `ParameterEncoding`

**Comment by startupthekid** [comment]
@jasi that's a good point. It may be better to use our own encoding that mirrors Alamofire.

@justinmakaila something else I'm concerned about is supporting parameters in an upload request.
In the scenario where someone uploads a file and needs to attach that reference to another model, that can't currently be done in Alamofire. 

For example I'm using feathersjs on my backend to supports before and after hooks:

```javascript
blobService.before({
  all: sharedAuthHooks,
  // Verify that the postID parameter exists and that it refers to a real post.
  create(hook) {
    const { params } = hook;
    const { postID } = params;
    if (typeof postID === 'undefined') {
      return Promise.reject(new errors.BadRequest('Invalid postID parameter'));
    }
    // Find a post with that id, error will be thrown if none exists
    return postService.get(postID).then(() => hook);
  }
});


blobService.after({
  // After a blob is created, attach the id to the post.
  create(hook) {
    const { result, data } = hook;
    const { id } = result;
    const { postID } = data;
    // Update the associated post with the blob id
    return postService.patch(postID, { blob: id }, {}).then(() => hook);
  }
});
```

Before a blob (a file object) is created, it verifies that a postID parameter is sent and that that post exists. After the creation occurs, the blob id is then attached to the post. But with Alamofire, you can't attach parameters to a file upload.

The reason I'm worried about that is because in applications that will introduce multiple points of failure in similar situations. Instead of relying on a single source of truth on the backend where parameters are verified and the appropriate models are updated, each client has to ensure that post-creation, the correct updating takes place. The more we can do to mitigate that risk that better but I'm not sure how with Alamofire currently.

**Comment by justinmakaila** [comment]
@startupthekid I think it should be possible for us to utilize the `encodingCompletion` invocation to add `parameters` from the target. All I'm doing is taking the encoded request and immediately kicking it off.

**Comment by jasl** [comment]
If we refactor the `ParameterEncoding`, keeping the same behaviour both with normal request and multipart upload is possible and simple
I've done this for my Moya fork, [details here](https://github.com/jasl/MoyaX/blob/master/Sources/Backends/AlamofireBackend.swift#L70-L134)

**Comment by justinmakaila** [comment]
The only thing I don't like about mirroring the `Alamofire.ParameterEncoding` to a custom `Moya.ParameterEncoding` (rather than the typealias) is that we tie ourselves to `Alamofire` updates. As their `ParameterEncoding` changes, we have to update ours. I'd rather us be able to abstract it in `Moya` land, transforming it into `Alamofire` land.

**Comment by jasl** [comment]
That's may not be an issue, for Cocoapods or Charthage, we can lock the Alamofire's version, and for 3.x, Alamofire would unlikely change `ParameterEncoding` (and `ParameterEncoding` should be a stable component according to its commit logs)

**Comment by jasl** [comment]
That's should not be an issue, for Cocoapods or Charthage, we can lock the Alamofire's version, and for 3.x, Alamofire would unlikely change `ParameterEncoding` (and `ParameterEncoding` should be a stable component according to its commit logs)

**Comment by justinmakaila** [comment]
Closing in favor of #483 and f3f7570dcf875d2c95cae41397176c4577cfc555

**Pull request closed without merging**
