### PR TITLE
Stubbed responses from files for TargetType

### PR DESCRIPTION
**Pull request by scottrhoyt**
This is meant to address an issue that I have come across in using `sampleData` to return responses of moderate complexity: `TargetType`s quickly get bloated and harder to read. This works against one of the main use cases for Moya: better organization of client API code. This has also popped up in a number of issues/PRs (e.g. #866, #603, #600, etc.).

The solution provided here is to write a helper function in `TargetType` (`stubbedResponse`) to load stubbed responses from a file. The intended usage is:

```swift
var sampleData: Data {
  switch self {
  case .users:
    return stubbedResponse("Users")
  case .profile:
    return stubbedResponse("Profile")
  }
}
```

This is accomplished by assuming that the file exists in the main bundle and that it has a "json" extension, but both of those default values can be overridden at the call site. If the data cannot be successfully loaded, the function will trap in debug mode (via `assert`) or just return an empty data in release config.

I'd love to get feedback in general, but here are some specific things:

* What do you think about the function name? I also considered `bundledResponse` to allow room for it to be differentiated from other ways of finding the stubbed response (e.g. via file URL so that one can avoid bundling test data with a production app).
* What do you think about the `assert()` behavior? I like this because devs will know right away in testing that the stubbed response can't be loaded as opposed to needing to debug a failing test because of a typo or the file being in a different bundle. However, even though it should be fine I am nervous letting an `assert` get into a production app because of high consequence if for some reason it doesn't work correctly. I'm also not sure if this will just hang a CI build or crash the test and cause it to fail. It is also untestable to my knowledge. The alternative I considered was just printing a warning message and returning an empty `Data` always. This is lower risk but possibly harder to debug. It's probably the way to go.

Another thing to consider is if we go further to encourage that test data be stored in files, we bring up some of the concerns in #425. We might want to consider alternatives to encouraging testing that don't require users to bundle production apps with test data/code. I'm a big believer of keeping testing and dev code/data out of production apps. I think it is less clean and the risk of unintended consequences is too high. It would, however, require a change in philosophy from Moya forcing testing to supporting testing. This was also talked about quite a bit in #861.

*Note: I'll add docs and CHANGELOG after incorporating feedback*

### CODE REVIEW

**Comment by scottrhoyt** [comment]
I went ahead an renamed the function to `stubbedResponses(forFileNamed:)`. What do you guys think?

**Comment by scottrhoyt** [comment]
Oops. Messed up a rebase it looks like. Let me retry.

**Comment by scottrhoyt** [comment]
Looks good now.

**Comment by BasThomas** [comment]
FWIW, I can't really think of a *better* function name. About the `assert`: I think this is the best option here.

**Comment by BasThomas** [comment]
> I'm also not sure if this will just hang a CI build or crash the test and cause it to fail.

... but we should definitely test this before doing so.

**Comment by scottrhoyt** [comment]
I'm pretty sure it will behave the same way as a `fatalError()` but I will open up a test branch here and throw an `assert` in to see what happens.

**Comment by scottrhoyt** [comment]
According to [this failed build](https://circleci.com/gh/Moya/Moya/1159?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) it looks like it behaves the way we want it to.

**Comment by BasThomas** [comment]
Hmm, does `sampleResponse` make sense for the function name?

**Comment by justinmakaila** [comment]
Maybe it's just me, but does this really belong in Moya? It seems like it's just sugar that could be implemented on a per-client basis. As OP said, this is only really relevant for testing, and this is stuff that should be coming from your network layer, rather than Moya itself.

**Comment by scottrhoyt** [comment]
@justinmakaila I agree that point should be discussed. We should consider whether or not Moya needs a rethink on how it handles testing. I think it might.

However, if the current approach holds, then we advocate that test data should be provided by `TargetType`s. Since it's not ideal to provide most real world test data from code, we should provide the tools necessary to load it from files. Sure, it might be pretty trivial stuff, but at least we could update our documentation and/or demos to show how it's likely to look in the real world instead of counting on users to come to this same conclusion.

**Comment by scottrhoyt** [comment]
@BasThomas, I'm pretty indifferent to the two names. I still slightly prefer omitting the first argument label, but that's just my personal style.

**Comment by justinmakaila** [comment]
I don't think it's on us to provide tools for loading the sample data in an opinionated format.

For instance, in my most recent networking library, I have this ((pardon the space formatting...):
```
  var sampleData: Data {
    switch self {
      // ...
        case .verify:
            return try! JSON([
                "isValid": true
            ]).rawData()
        case .graphOperation:
            return try! JSON([
                "data": [:],
                "errors": []
            ]).rawData()
        case .checkProgramCode:
            return try! JSON([
                "isValid": true
            ]).rawData()
  }
}
``` 
I think we're headed down a slippery slope if we're just adding sugar.

The end user of Moya is the one implementing `TargetType`, and should be deciding where and how to load their data for their stubbed responses. If they're not building with tests in mind, they're going to put `return Data()`, and if they are, they probably have some custom way that they're going to serve their responses anyway.

**Comment by scottrhoyt** [comment]
I don't disagree with you. However, I just think our viewpoint might be in disagreement with the stated goal of Moya:

> Treats test stubs as first-class citizens so unit testing is super-easy.

By forcing `TargetType`s to provide a `sampleData`, it seems we are already on the slippery slope of recommending testing patterns. This PR goes not much further really, as it's just providing an optional tool and there is nothing to say you can't still do it the old way. 

On the flip side, judging by the issues that I referenced above, some users do run into the problem of our documented pattern not going far enough to support testing with real world responses from moderate complexity APIs. The goal of this PR was to prevent all those users from having to write this method themselves, not represent my personal feeling on how testing should be done.

Personally, I think tests data should be in the test project and supplied by the test objects, not bundled with the main app. But that approach has it's own drawbacks, so I respect that Moya is trying to do it differently.

**Comment by justinmakaila** [comment]
But isn't providing `sampleData` and built in mocks/stubbing enough to make it a first class citizen?

API resource models are literally providing their `Data` representation.

I'm just afraid that we'll start adding something like this while everyone has divergent ideas will put us in the same place we were when people started writing JSON extensions and saying "oh well 90% of services deliver data in this form, why don't we build in JSON handling with this provider?".

**Comment by scottrhoyt** [comment]
That is fair. To me this is less divergent and more a natural extension of the tools we provide for testing, but I totally understand the pushback for going even a bit further in this direction as it's further promoting a specific testing pattern that doesn't sit well with everyone... including sometimes myself.

This is code that I personally use to reduce the pain of managing complex responses for sample data, but it's not a one-size-fits-all approach. Issues led me to believe others were having the same problems, so I offered my help. We don't have to include it though.

If you had some other ideas on how we could make testing more open and flexible to all approaches (including keeping test data in test bundles) while still keeping it first class, I would love to see that PR come through. 👍

**Comment by BasThomas** [comment]
I think the least we can do here (especially since I think @justinmakaila makes a fair point), is to include this snippet in the docs. Just as we did with some of the String extensions. This then is also a reference point for future issues. :)

**Comment by scottrhoyt** [comment]
The consensus here looks like this isn't a good idea, so I will go ahead and close this.

**Comment by fjcaetano** [comment]
Hey @scottrhoyt, I'm also using a stubbed files approach and also wouldn't like to have these json files in the main bundle to be distributed with the app. Did you manage to add them to the test target without having to change the whole project membership?

**Pull request closed without merging**
