### PR TITLE
Support OS X

### PR DESCRIPTION
**Pull request by mhuusko5**
Only thing breaking OS X compatibility was UIImage use. Easy fix.

### CODE REVIEW

**Comment by petester42** [comment]
Thats a good way to fix that. There are a couple of issues though.

1. The podspec does not pass linting you can try it out by doing `pod lib lint`
2. There should probably be a demo target for os x
3. Tests should also be added for os x

**Comment by ashfurrow** [comment]
Cool! I can handle updating the tests. What's the lint error?

**Comment by mhuusko5** [comment]
It had to do with Alamofire and deployment targets. Just pushed a fix.

**Comment by ashfurrow** [comment]
Awesome! I'll take a look at tests when I get home. Thanks again!

**Comment by ashfurrow** [comment]
Going to merge this as-is; I've opened https://github.com/Moya/Moya/issues/265 to address the CI. Thanks!

**Comment by mhuusko5** [comment]
Yayyy, thanks

**Comment by mhuusko5** [comment]
Out of curiosity, what's the flow from tag necessitating change, to new CocoaPods version? Would be cool to see OS X support on trunk, but not sure if there's a lot to do (for example, if addressing the CI issue is pre-req) before making a push?

**Comment by ashfurrow** [comment]
Hey, so that's a great question. Normally, tags are created with the [automated release task](https://github.com/Moya/Moya/blob/3f657edb6dcb2346754d65828b898e2b58cf95a4/Rakefile#L28). I just forgot to run the task after merging this >.<

**Comment by mhuusko5** [comment]
Okeedoke, good to know

**Comment by ashfurrow** [comment]
New version is up: https://raw.githubusercontent.com/CocoaPods/Specs/87704665c95c9c49e1324991ee94142c3504ded6/Specs/Moya/4.1.0/Moya.podspec.json

**Pull request merged**
