### PR TITLE
Cleanup closures

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by BasThomas** [comment]
Yeah, I saw that. Let me take a look.

**Comment by BasThomas** [comment]
Ah, it seems like in this few changes, I did not yet change `Cancellable`'s `cancelled` to `isCancelled` yet.

**Comment by BasThomas** [comment]
Added the bool renaming to the `CHANGELOG` in d77c261.

**Comment by pedrovereza** [comment]
Let me try to combine this PR with #775 #776 and #777 :wink:

**Comment by pedrovereza** [comment]
@BasThomas Ok, branch `cleanups` should have all changes. Can you open a new PR out of that branch? I'll close this and the others PR to avoid confusion 😄

**Comment by BasThomas** [comment]
Done, thanks a lot! 🙌

**Pull request closed without merging**
