### PR TITLE
Updating branch development-swift-5.1 

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Targeting development 5.1 branch
* Updating and resolving conflicts of development-swift-5.1 with development.
* Improving the atomic code follow up of #1952 

cc @BasThomas

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
The CI is only failing on the Danger, which is the same issue of the original branch, and although we have to investigate it, should be fine for this one :)

**Comment by LucianoPAlmeida** [comment]
Right, @sunshinejr @BasThomas, conflicts solved, a couple of tests fixed because TSAN was not liking them very much \o/ 
Let's see what's the CI thinks about it :)) 
Like the original, this targets the @BasThomas branch from #1931, so once we merge this it will be updated 👍

**Comment by sunshinejr** [comment]
ok this update PRs got really messy... :D @LucianoPAlmeida could you maybe a create a new branch off of `development`, pick the commits from @BasThomas and add yours at the top? and then create a new PR? this will be a lot easier as there is too much noise that's already merged 😿

**Comment by LucianoPAlmeida** [comment]
I could do that :) or maybe just rebase with development 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sunshinejr** [comment]
@LucianoPAlmeida I'm fine with whatever that works for you!

**Comment by LucianoPAlmeida** [comment]
Ahhh @sunshinejr I think those commits are here because the target is Bas branch and the commits aren’t the because it is not updated with developer, merging this should do it. What do you think about merging this as it is in bad branch and continue from there? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sunshinejr** [comment]
@LucianoPAlmeida yeah that's why I suggested a new PR instead, this way it will be at least readable :D

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida yeah that's why I suggested a new PR instead so it will be readable again (both commits/content) :D

Ohh sure, I'll do it as soon as possible then :)

**Comment by BasThomas** [comment]
Sorry for not being able to jump in here — was busy with other things. See that this is now done; thanks @LucianoPAlmeida @sunshinejr! :)

**Comment by LucianoPAlmeida** [comment]
No worries @BasThomas, we got that covered :)

**Pull request closed without merging**
