### PR TITLE
Updated podspec to use RxSwift 2.x

### LINKED ISSUE #386: RxSwift 2.1.x
You state that Moya `6.1.1` has obtained compatibility with RxSwift `2.1.x`, however, the subspec still states it needs `~> 2.0.0`

### PR DESCRIPTION
**Pull request by philipengberg**
Fixes #386

### CODE REVIEW

**Comment by ashfurrow** [comment]
Fab, thanks!

**Comment by ashfurrow** [comment]
Hey there! Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by philipengberg** [comment]
Cool, thanks! Since I have never published a cocoapod before: Does this change require a new release to cocoapods?

**Comment by ashfurrow** [comment]
Ah yes! I forgot to release, let me do that now.

**Comment by ashfurrow** [comment]
Cooooool, this has been released as 6.1.2. Let me know if that works!

**Comment by philipengberg** [comment]
It works, thanks a lot!

**Pull request merged**
