### PR TITLE
#246 Add Cartfile and separate sections for cocoapods and carthage in README.md

### PR DESCRIPTION
**Pull request by gregpardo**
Giving this little one a shot too.

### CODE REVIEW

**Comment by orta** [comment]
:+1:

**Comment by aschuch** [comment]
Shouldn't the Cartfile specify `~> 2.0` instead of `~> 2.0.2`? Not sure about the exact implications of this, but pinning to a major version seems to be the better choice here. Opinions?

**Comment by gregpardo** [comment]
Yes I mentioned that [here](https://github.com/Moya/Moya/issues/246#issuecomment-146257866). I can make another pull request if needed unless someone wants to push a quick fix.

**Comment by aschuch** [comment]
Go for it :)

**Pull request merged**
