### PR TITLE
Transfers to Moya organization

### PR DESCRIPTION
**Pull request by ashfurrow**
Little odds and ends. I'm sure we'll be fixing these for a few weeks to come :)

### CODE REVIEW

**Comment by esttorhe** [comment]
Not a contributor/maintainer but it looks good :ok_hand:

**Comment by ashfurrow** [comment]
Well, that's fixed. Merge away!

**Comment by esttorhe** [comment]
Ha! :bow: 

Much appreciated

**Comment by ashfurrow** [comment]
@esttorhe you forgot to merge!

**Comment by ashfurrow** [comment]
:bow:

**Comment by esttorhe** [comment]
i thought I clicked the button but apparently I did not ¯\\\_(ツ)\_/¯

Fixed that though

**Pull request merged**
