### PR TITLE
ReactiveMoya compilation fixes

### LINKED ISSUE #254: Support Alamofire 3
If Moya is exposing Alamofire anywhere in Moya's public API then Moya also needs a major versions bump.

### PR DESCRIPTION
**Pull request by JRHeaton**
Fixes #254

### CODE REVIEW

**Comment by orta** [comment]
This sounds right, it would have accepted Alamofire 3.0 as it came out today

**Comment by ashfurrow** [comment]
Cool, thanks for fixing this! 

Alamofire changed from `ErrorType`. [In 3.0](https://github.com/Alamofire/Alamofire/blob/2beb1e3b6ca9349badcd9cbba1a7efad8bc43c89/Source/ResponseSerialization.swift#L84-L87) it uses `NSError` but [in 2.0](https://github.com/Alamofire/Alamofire/blob/d69b3eee05aeab1db8d268978193fcbabbd7cb09/Source/ResponseSerialization.swift#L78-L81) it uses `ErrorType`. As @orta pointed out in https://github.com/Moya/Moya/issues/254 , this will require a release of Moya 4.0, which is totally ok with me. 

@JRHeaton Releasing 4.0 would require a few additional changes:

- Update from `~> 2.0` to `~. 3.0` for the Alamofire dependency in all podspecs.
- `pod install` within the `Demo` directory.
- Fix source code issues from update to Alamofire.
- Update this PR description to say "Fixes #254" s GitHub closes that issue.
- Update the changelog.

Would you like to take this on? If you can't, don't worry – happy to finish up. Thanks again! :100:

**Comment by JRHeaton** [comment]
I updated everything as you described. Let me know if anything needs changed.

**Comment by ashfurrow** [comment]
Awesome, this looks great! :cake:

**Comment by ashfurrow** [comment]
Super! This has been pushed to CocoaPods trunk: https://raw.githubusercontent.com/CocoaPods/Specs/372b7bdbf6c5a350b1de6bdb0843f3f6c90ecc30/Specs/Moya/4.0.0/Moya.podspec.json

Thanks again for being on the ball, @JRHeaton :8ball:

**Pull request merged**
