### PR TITLE
Xcode 9.3 test run & dependencies update.

### PR DESCRIPTION
**Pull request by sunshinejr**
I've run a test for Swift 4.1 with Moya and it seems to be working just fine without any warnings. Only change I think was that there is this new file, `IDEWorkspaceChecks.plist`, and it seems that [it's better committing this file instead of ignoring it](https://twitter.com/NeoNacho/status/978339756374351872), so I've did it as well.

Apart from that I've updated the dependencies for SPM & Carthage.

### CODE REVIEW

**Comment by Dschee** [comment]
When specifying this branch and running `carthage update --platform ios` the build of RxMoya failed. I just created a new branch named `xcode_9.3` which includes this branch and the branch `swiftlint-fix` which is part of #1619. Now it works.

**Comment by sunshinejr** [comment]
@Dschee yeah because this one doesn't fix the Carthage problem, that's why you have these errors. After fixing Carthage Swift 4.1 will work without any additional works. This one just adds a file that Xcode 9.3 added and updates dependencies, that's why it's targeted to the `development` branch as well.

**Comment by SD10** [comment]
@sunshinejr Can we merge this one?

**Comment by sunshinejr** [comment]
@SD10 Yeah, it's good to go.

**Pull request merged**
