### PR TITLE
Rename functions in PluginType to comply with design guidelines

### PR DESCRIPTION
**Pull request by pedrovereza**
`willSendRequest` renamed to `willSend`.
`didReceiveResponse` renamed to `didReceive`.
`prepareRequest ` renamed to `prepare`.
`processResponse` renamed to `process`.

### CODE REVIEW

**Comment by BasThomas** [comment]
Totally unrelated, by why is the testing class for the `NetworkLoggerPlugin` called `NetworkLogginPluginSpec`? Seems like a pretty strange typo 😬. Or am I missing something there?

**Comment by ashfurrow** [comment]
It's common in Ruby to call them `Spec`, probably from there. Either way is fine, most of my projects have both 😆

**Comment by BasThomas** [comment]
Was actually referring to the `Pluggin` part. ;)

**Comment by ashfurrow** [comment]
Mmmm, yeah that's probably just a typo ¯\\_(ツ)_/¯

**Comment by pedrovereza** [comment]
Renaming the file makes sense 👍  

Can we make the change in another PR?

**Comment by BasThomas** [comment]
Sure, will do!

**Comment by pedrovereza** [comment]
BTW, do we need anything else done in this PR? Or can it be merged?

**Comment by BasThomas** [comment]
Should be good to go! Thanks @pedrovereza 🙌

**Comment by pedrovereza** [comment]
👊

**Pull request merged**
