### PR TITLE
Sync master with development

### PR DESCRIPTION
**Pull request by SD10**
### Summary:
Just syncing back `master` and `development`. Looks like there will be a conflict

### CODE REVIEW

**Comment by SD10** [comment]
@pedrovereza I'm not sure what you mean by "recreate". Sorry for letting this drag on. I was going to solve it by re-running bundler on `development` to replace the lockfile

**Comment by pedrovereza** [comment]
@SD10 I meant create a new branch from the top of `master` and call it `development`, instead of trying to merge `master` into `development`.

Unless there's anything on `development` that didn't make it to `master` yet 😄

**Comment by SD10** [comment]
@pedrovereza I see what you mean. There's 43 commits on `development` that aren't on `master` yet, as we usually do the beta releases from the `development` branch

**Comment by SD10** [comment]
Sorry, it took me so long to resolve this. I had a nightmare of a month at work. Closing this as it's no longer necessary. I resolved the conflict on `development` by running `bundle update` and pushed

**Pull request closed without merging**
