### PR TITLE
Invoke completion even when cancellable immediately cancelled #531

### PR DESCRIPTION
**Pull request by jefflovejapan**
I added some tests to verify correct behavior but can't get master to build. Applying the patch to 6.5.0 builds and passes though.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks for the PR! Don't mind the SwiftLint warnings. 

CI is failing due to a problem finding the `isCancelled` property – you said it's working for you locally? I can try and take a look here too.

**Comment by jefflovejapan** [comment]
No sweat! I was having issues building master, so I followed [this recommendation](https://github.com/Moya/Moya/issues/525#issuecomment-230854674) and branched from 6.5.0 (where it worked), but I saw that there were some changes to `Moya.request` in master, so figured it was better to apply the patch in both places there even though I couldn't get it to build locally.

**Comment by jefflovejapan** [comment]
I see that there are now two failing tests, [here](https://github.com/Moya/Moya/blob/master/Demo/Tests/MoyaProviderSpec.swift#L225) and [here](https://github.com/Moya/Moya/blob/master/Demo/Tests/MoyaProviderSpec.swift#L248). Since these appear to be the opposite of the desired behavior in #531 it might make sense to remove them.

**Comment by ashfurrow** [comment]
I agree, sound good 👍

**Comment by colinta** [comment]
Don't remove them - reverse the expectation!

**Comment by colinta** [comment]
e.g. 

```diff
-it("never calls completion if cancelled immediately") {
+it("calls completion if cancelled immediately") {
```

**Comment by colinta** [comment]
Awesome!

**Comment by ashfurrow** [comment]
Mergin'!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by colinta** [comment]
I was looking into refactoring `sendUpload` and `sendRequest` to use a shared `sendAlamofireRequest` method, and I noticed that this line wasn't updated to return an error response:

https://github.com/jefflovejapan/Moya/blob/05c2a77cbd4bff9e2ac07fe18ac1006b4b4a3da3/Source/Moya.swift#L440

I want to make sure it *should* be added, because I'm adding it to my changes.  But if it was deliberately skipped (maybe it's redundant? I didn't look too closely, but that doesn't seem to be the case) let me know!

**Comment by colinta** [comment]
Oh shoot, also the plugins aren't notified of cancellations.  I'm going to add an internal helper:

```swift
    internal func cancelCompletion(completion: Moya.Completion) {
        let error = Moya.Error.Underlying(NSError(domain: NSURLErrorDomain, code: NSURLErrorCancelled, userInfo: nil))
        plugins.forEach { $0.didReceiveResponse(.Failure(error), target: target) }
        completion(result: .Failure(error))
    }
```

**Comment by colinta** [comment]
See #543 for my changes

**Comment by jefflovejapan** [comment]
@colinta No you're right, this was an oversight on my part. Thanks for fixing!

**Comment by colinta** [comment]
😁👍

**Pull request merged**
