### PR TITLE
[Swift 3.0] Update to new Alamofire Requests & Progress API.

### PR DESCRIPTION
**Pull request by sunshinejr**
So due to [Alamofire#1455](https://github.com/Alamofire/Alamofire/pull/1455) change, we have to update our progress blocks as well. For now I've just updated the new Alamofire's Progress API to our existing Progress API. If we should update to two blocks instead of one (`downloadProgress`, `uploadProgress`) is eligible for discussion. 

More info #608.

Cheers! 🐼

### CODE REVIEW

**Comment by edwardvalentini** [comment]
this looks great!

**Comment by edwardvalentini** [comment]
Oh no - alamofire deprecated the Int64 variants for the progress handlers

**Comment by orta** [comment]
sounds like this is definitely a major version bump then 👍

**Comment by edwardvalentini** [comment]
I'm working on a PR for this right now.

**Comment by edwardvalentini** [comment]
even though 7.0.0 was released recently - does it make sense to move to 8.0.0 as @orta suggests?

**Comment by BasThomas** [comment]
I too think that makes the most sense, yeah.

**Comment by edwardvalentini** [comment]
I'm testing #618 #613 #608 on my own fork and everything seems to be working smoothly 👍

**Comment by sunshinejr** [comment]
Okay, I think that it can be merged to the main Swift-3.0 repo, and make sure that Moya builds, and if there are any issues about this PR we can make a new one with fixes.

**Pull request merged**
