### PR TITLE
Fixed two small typos in Endpoints.md

### PR DESCRIPTION
**Pull request by regexident**

### CODE REVIEW

**Comment by esttorhe** [comment]
Thanks

**Comment by esttorhe** [comment]
Umm. Apparently cant merge from my phone due to the failed tests.
Will check from computer later

**Comment by ashfurrow** [comment]
@regexident Thanks a lot!

@esttorhe CI failures are intermittent (see #176). When this happens to me, I [do this](http://www.idownloadblog.com/2014/06/19/ios-8-safari-request-desktop-site/)

**Comment by regexident** [comment]
"All checks have failed" makes it sound pretty horrible.
Like I BROKE ALL THE THINGS with just plain english. :joy:

No biggie.

Found a typo and thought "nah, I can't spam them with a PR for a single cosmetic character change". 
So I looked for another one. Found one and thought "now we're talking!". :smile:

**Comment by ashfurrow** [comment]
Ha, yeah we need to get CI working again.

**Comment by esttorhe** [comment]
:+1:  good tip Ash; I'll do that next time

**Pull request merged**
