### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by kickbell**
Added dependency versions supported for each version of moya.

I'm a junior developer, and I remember that moya version 14.0.0 was not supported in RxSwift version 6 and crashed. I hope this contribution is helpful.

### CODE REVIEW

**Comment by AndrewSB** [comment]
hey @kickbell! thanks a bunch for making this change 😄 

i don't think we can merge this in with some of the values being empty, do you know what the values are for the older versions that you didn't fill out?

**Comment by kickbell** [comment]
hello @AndrewSB 😄. 

I forked from the master branch 10 days ago, and only modified the Readme.md file as above.

What should I do?

**Comment by AndrewSB** [comment]
i wasn't totally clear, my bad. i meant adding values for the older versions in the new columns you've added here. if we're to add this to the docs, it should probably be complete


Screen Shot 2022-08-11 at 6 13 15 PM

**Comment by kickbell** [comment]
Ah, I understand what you mean. I'll fix it. Thanks for the quick feedback! @AndrewSB

**Comment by kickbell** [comment]
Is circleci failing because of swiftlint? What more should I do?

https://app.circleci.com/pipelines/github/Moya/Moya/334/workflows/246325f0-2910-4b78-aa08-8a275b71edef/jobs/4446

**Pull request merged**
