### PR TITLE
get response and error when use Alamofire validation

### PR DESCRIPTION
**Pull request by yanamura3**
I tried to solve this problem.
https://github.com/Moya/Moya/issues/975

This change does not affect to current behavior, so I pull request to master branch.

## solved problem
when use Alamofire validation, we cannot get response in failure result.

## how to solved
check the Target is using "validate" in convertResponseToResult()

### CODE REVIEW

**Comment by scottrhoyt** [comment]
Thanks for the contribution @yanamura3!

I have to think about this one for a second. Something feels a little off about transforming an `AFError` into a `MoyaError` like this. I don't know that it is a bad approach, it just feels unique as to how we handle other underlying errors. Also, having it depend on `validate` and possibly not doing the transform if a response doesn't exist feel a bit too non-deterministic.

On the other hand, this is a clever way to get the changes necessary for #975! It is technically a breaking change, though. If someone wrote code that looks for the a `AFError. responseValidationFailed` embedded in a `MoyaError.underyling`, their code will break with this update. Worse, it would probably be silent--no compiler error.

In the light that it would be a breaking change, I'm leaning towards it being better to just add an optional `Response` value to `MoyaError.underyling`, but that's not a strong opinion.

Would love to hear what other @Moya/contributors think of this approach.

**Comment by yanamura3** [comment]
@scottrhoyt  Thanks for comments!

You are right, if someone handling responseValidationFailed, my change will be a breaking change..
> It is technically a breaking change, though. If someone wrote code that looks for the a AFError. responseValidationFailed embedded in a MoyaError.underyling, their code will break with this update. Worse, it would probably be silent--no compiler error.

I think my approach is not best solution ( just patch solution ).
It's may be better to solve #975 next major version.

**Comment by gperdomor** [comment]
@scottrhoyt check  #993 please, i add the response to `MoyaError.underyling`

**Comment by gperdomor** [comment]
@yanamura3 this was solved in #993 :D

**Pull request closed without merging**
