### PR TITLE
Swift 3 availability tags

### PR DESCRIPTION
**Pull request by BasThomas**
This PR implements availability tags for the changed function names from the Swift 2 to Swift 3 migration.

This makes the lifes of users making the switch easier, as the compiler provides fix-its for the functions that need renaming (as seen [here](https://github.com/Moya/Moya/issues/888#issuecomment-270004469))

The tags added are as follows

- [x] Renamed endpointByAdding(parameters:httpHeaderFields:parameterEncoding) to adding(parameters:httpHeaderFields:parameterEncoding)
- [x] Renamed endpointByAddingParameterEncoding to adding(newParameterEncoding:)
- [x] Renamed endpointByAddingParameters to adding(newParameters:)
- [x] Renamed endpointByAddingHTTPHeaders to adding(newHttpHeaderFields:)
- [x] Renamed StructTarget to MultiTarget
- [x] Renamed notifyPluginsOfImpendingStub(request:) to notifyPluginsOfImpendingStub(for:)
- [x] Renamed request(token:) to simply request(:_) (ReactiveSwift)
- [x] Renamed filterStatusCodes(:) to filter(statusCodes:) (and filterStatusCode(:) to filter(statusCode:))
- [x] willSendRequest renamed to willSend
- [x] didReceiveResponse renamed to didReceive
- [x] Renamed ReactiveCocoaMoyaProvider to ReactiveSwiftMoyaProvider

~~The yet-to-be-done functions have been commented out:~~

- ~~`extension ReactiveSwiftMoyaProvider` has a `Use of undeclared type 'ReactiveSwiftMoyaProvider'` error;~~
- ~~`public func filterStatusCodes(range: ClosedInterval<Int>) throws -> Response` has a `'ClosedInterval' has been renamed to 'ClosedRange'` error.~~

~~... and I have no idea how to fix either of these.~~

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool! Looks great. I'm fine with leaving those commented out for documentation's sake, up to you. Could we provide an empty `ReactiveSwiftMoyaProvider` implementation that's marked as unavailable maybe?

**Comment by BasThomas** [comment]
But we *do* [use it](https://github.com/Moya/Moya/blob/ea331f79c534db1334b93b0d5526bfeb5227a6d1/Source/ReactiveSwift/ReactiveSwiftMoyaProvider.swift#L8), and it should not be unavailable, right?

**Comment by BasThomas** [comment]
And if we do leave them commented out, I'd like to add an explanation for that before merging.

**Comment by BasThomas** [comment]
It would also be **awesome** if somebody could test this (by converting a pre-8.0.0 project to this branch.

**Comment by BasThomas** [comment]
Hmm, I suppose we can just fix `public func filterStatusCodes(range: ClosedInterval<Int>) throws -> Response has a 'ClosedInterval' has been renamed to 'ClosedRange' error.` by changing `ClosedInterval` to `ClosedRange`, as the compiler will see that error first (probably?) and the signatures then match.

**Comment by BasThomas** [comment]
Been able to fix the two remaining functions as well. Imported `ReactiveSwift` et voilà.

If someone could help me squashing these commits, please let me know. Think it can use some cleanup, but I am not sure how to proceed myself.

**Comment by BasThomas** [comment]
Welp, CI is failing. @scottrhoyt @AndrewSB any idea why the files can't be found?

**Comment by BasThomas** [comment]
I get the same error building just the framework locally, using the `Demo.xcworkspace` works just fine.

**Comment by scottrhoyt** [comment]
I'll take a look, @BasThomas.

**Comment by scottrhoyt** [comment]
I think when you merged `master` after #885 (c22ef57f6364a1d0efb304916b2acd3929852319), you resolved the merge conflicts in the Xcode project by inserting the old references back into the project along with the new ones. I think this should branch should be rebased off of `master` resolving those conflicts with the new references. Do you want to give that a try or I can do it if you'd like?

**Comment by scottrhoyt** [comment]
Xcode project merge conflicts are 😭.

**Comment by scottrhoyt** [comment]
`Demo.xcworkspace` will still work fine because it uses a cocoapods integration that doesn't rely on the main Xcode project.

**Comment by BasThomas** [comment]
If you could do so, please go ahead. I'd probably have closed this and started with a clean slate. 🙈

**Comment by scottrhoyt** [comment]
Surely. I'll probably have that done in ~30 minutes. I will let you know.

**Comment by scottrhoyt** [comment]
@BasThomas, I rebased and pushed to `swift3-availability-2` just so you can check to see if it still looks good to you. If it does, it will delete that branch and push here. Sound good?

**Comment by scottrhoyt** [comment]
I also fixed some problems with combining Availability info for Moya and ReactiveMoya.

**Comment by BasThomas** [comment]
Yes, looks good!

**Comment by BasThomas** [comment]
Thanks for the help @scottrhoyt! I think this should be good to go now.

**Comment by BasThomas** [comment]
Oh, one more thing: we might want to move the `Moya.Error` unavailability tag to the `MoyaAvailability.swift` file instead of letting it "linger" in `MoyaErrror.swift`.

**Comment by BasThomas** [comment]
Can someone review and merge? Also, I think we can release `8.0.0` once merged! 🎉

**Comment by BasThomas** [comment]
Or we could just keep them. We'll see. :)

**Comment by scottrhoyt** [comment]
I agree they will be a great addition for the migration and certainly useful for a while. But when the changes have sat for a while it might be nice to reduce the API surface area (primarily for code completion), reduce instances of `fatalError()` in the code base, and get a percentage point of test coverage back if no one needs them anymore. :)

**Pull request merged**
