### PR TITLE
Bump RxSwift to 4.1

### PR DESCRIPTION
**Pull request by lucas34**
Link to issue #1530
Updating RxSwift to 4.1

Pod lib lint -> Pass
swift build -> Pass

### CODE REVIEW

**Comment by lucas34** [comment]
I forgot to update the Changelog

**Comment by sunshinejr** [comment]
Hey @lucas34. I'm curious: why are we doing this change? '~> 4.0' should be enough to use with both 4.0 and 4.1. Unless something big happened between these 2 releases that we should support in our code?

**Comment by lucas34** [comment]
You are right. I was wondering if I should update only the .resolved files. There is no issue as keeping ~> 4.0 in both Podspec and cartfile. 

This PR is mostly to give the latest released version of the dependency at this date when using 
`carthage bootstrap` or `swift package resolve`

**Comment by sunshinejr** [comment]
Oh, now I understand! Thanks @lucas34, nice catch!

**Pull request merged**
