### PR TITLE
update circle ci xcode version to 8.3

### LINKED ISSUE #1039: Carthage bootstrap failing on CI
A more descriptive error in https://circleci.com/gh/Moya/Moya/1316
> Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Sources/RxMoya/RxMoyaProvider.swift:2:8: **error: module compiled with Swift 3.1 cannot be imported in Swift 3.0.2**: /Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Carthage/Build/iOS/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -project /Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme "RxMoya iOS" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

Not so verbose in https://circleci.com/gh/Moya/Moya/1319 🤔 

> A shell task (/usr/bin/xcrun xcodebuild -project /Users/distiller/Moya/carthage_test/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme "ReactiveMoya iOS" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

I'm planing to take a deeper look on it over the weekend, but I could definitely use some help 😉

### PR DESCRIPTION
**Pull request by AndrewSB**
This attempts to fix #1039 

Let's see if CI passes on this commit

### CODE REVIEW

**Comment by AndrewSB** [comment]
Getting different errors! This looks like progress.

It seems as if Swift 3.1 the _non breaking_ update, broke our tests. Right now, I can see that our `NetworkLoggerPlugin.init` calls in our tests are broken.

screen shot 2017-04-03 at 5 59 59 pm

The compiler error looks like it's related to the `output` param in the initializer.

```swift
public init(verbose: Bool = false, cURL: Bool = false, output: @escaping (_ separator: String, _ terminator: String, _ items: Any...) -> Void = NetworkLoggerPlugin.reversedPrint, responseDataFormatter: ((Data) -> (Data))? = nil) {
        self.cURL = cURL
        self.isVerbose = verbose
        self.output = output
        self.responseDataFormatter = responseDataFormatter
}
```

The definition says its expecting `output: @escaping (_ separator: String, _ terminator: String, _ items: Any...) -> Void`, but our initializer is just taking one param (`printing` in the screenshot), from the closure, and incorrectly not handling the other ones.

Does anyone who's more familiar with the `NetworkLoggerPlugin` or these tests know why that may be?

**Comment by pedrovereza** [comment]
@AndrewSB Good job! I almost got it right in https://github.com/Moya/Moya/commit/eefcf600139ed8fb787d5c936c0277fc024902ad, but only updated the dependencies I thought were causing the issue 😄 

And I'd say we can skip the unused arguments in the closure. Actually, I was hopping that `_, _, printing` would do the trick, but [it didn't](https://circleci.com/gh/Moya/Moya/1338) and I'm not sure why 🤔

**Comment by AndrewSB** [comment]
That was a good move @pedrovereza

Yeah, I thought that was really strange too- why weren't we `_, _`ing those params previously?

I just don't know much about that piece of the codebase, so I was hoping another contributor could jump in and enlighten us 😛

**Comment by pedrovereza** [comment]
@AndrewSB Ok, so it seems like `printing` actually groups all arguments

image

In fact, the `Any...` argument is accessed as `printing.2` in the test. I didn't know it was possible and (in the very quick search I did) could not find references about this feature.

Doesn't fix the problem but at least we know why it worked 😄

**Comment by BasThomas** [comment]
Maybe a stupid question, but how do I run the tests from Xcode now? Can't seem to do so from the Demo project, and opening the framework's `xcodeproj` complains of `Alamofire` missing (which makes sense, right?)

**Comment by BasThomas** [comment]
Also, though this should probably be tackled in another PR, updating the dependencies causes a bunch of warnings in the Demo project.

**Comment by AndrewSB** [comment]
Pedro: what scares me is that previously we just had printing, and from what I see in the contents of the test, it looks like it was an array, not a tuple (with three elements).
I'll do a git blame and figure out who wrote those tests when I'm back on a computer tonight- to ask them what they recommend doing


Bas: command-U when you're on one of the Moya targets should run the tests

**Comment by pedrovereza** [comment]
> and from what I can infer from the contents of the test, it looks like it was an array, not a tuple (with three elements).

I think it was a tuple 🤔 

```swift
 let stringArray: [String] = printing.2.map { $0 as? String }.flatMap { $0 }
```
Isn't `printing.2` returning the third argument (the array of `Any`)?

But you're right, if we can find who wrote the test just to confirm the intention it'd be better 👍

**Comment by AndrewSB** [comment]
Ohh, I missed that.

If that's how the tests are, then I feel pretty confident with just
continuing as we were
I wonder why the tests regressed with swift 3.1 then 🤔

**Comment by BasThomas** [comment]
@Andrew: Ah, but that is then complaining of Alamofire not being there. Which gives me an error, and cancels the tests.

**Comment by AndrewSB** [comment]
@BasThomas what's the complaint?

**Comment by BenEmdon** [comment]
Saw this PR had been sitting here for a bit, so I tried to see if I could help out.
Currently the syntax looks like this:
```swift
plugin = NetworkLoggerPlugin(verbose: true, output: { printing in
  let stringArray: [String] = printing.2.map { $0 as? String }.flatMap { $0 }
  ...
})
```
To reach the same functionality this will work:
```swift 
plugin = NetworkLoggerPlugin(verbose: true, output: { (_, _, printing: Any...) in
  let stringArray: [String] = printing.map { $0 as? String }.flatMap { $0 }
  ...
})
```
Hope this helps!

**Comment by pedrovereza** [comment]
@BenEmdon Awesome! I totally missed the `printing:` part 😄 

Do you feel like pushing a commit with this fix on branch `fix-carthage-ci-fail`? 😉

**Comment by BenEmdon** [comment]
@pedrovereza sure!

**Comment by BasThomas** [comment]
🙌👏 great teamwork, thanks for the fix!

**Pull request merged**
