### PR TITLE
Run SwiftLint only on debug builds

### LINKED ISSUE #1458: Error while updating Moya with carthge
Hello,
I'm using carthage version 0.26.2, and when trying to update with `carthage update --platform iOS` I get, only for Moya, this error:
```
*** Skipped installing Moya.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)."
*** Checking out Moya at "10.0.0" 
```

Here is my Cartfile:
```github "Moya/Moya" "10.0.0"```

Would you have any idea of why or how I could make this work ?

### PR DESCRIPTION
**Pull request by Dschee**
Attempts to fix problems with the SwiftLint script when building via Carthage.

Fixes #1458 and #1542. Intended to supersede #1615.
Related to #1616.

### CODE REVIEW

**Comment by sunshinejr** [comment]
I appreciate that you jumped in on this, @Dschee. However, we don't want to make the same mistake twice and just believe that this is working. Could you please create a step in Circle CI config that runs carthage script without SwiftLint installed?

**Comment by Dschee** [comment]
I just added something to the Circle CI config. Let's see what the result's gonna be ...

**Comment by Dschee** [comment]
The new step running this before SwiftLint install:

```
carthage build --no-skip-current --cache-builds
```

Resulted in a successful build of all Moya targets:

```
*** Building scheme "Moya" in Moya.xcodeproj
*** Building scheme "RxMoya" in Moya.xcodeproj
*** Building scheme "ReactiveMoya" in Moya.xcodeproj
```

Does this meet your expectations?

**Comment by SD10** [comment]
@Dschee Thanks for finding an alternative solution to removing part of our tooling

**Comment by Dschee** [comment]
Just as a side note: I had similar issues with SwiftLint and Carthage like I saw in several issues here in my own open source projects. This approach successfully fixed them all. That‘s why when I saw you were removing SwiftLint I felt like I should share my experience there.

**Pull request merged**
