### PR TITLE
Rename ReactiveCocoa to ReactiveSwift

### PR DESCRIPTION
**Pull request by BasThomas**
See #648

### CODE REVIEW

**Comment by BasThomas** [comment]
If anyone wants / has an idea on how to take [this](https://github.com/Moya/Moya/issues/648#issuecomment-263372164), please do!

> I was thinking we could include it as two subspecs, and deprecate the old one in favour of the new. To avoid repeating ourselves in the podspec, we can have the old deprecated subspec simply have a dependency on the new one. Does that make sense?

**Comment by BasThomas** [comment]
Could we simply do this? Without needing the `ss.source_files`?

```
s.subspec "ReactiveCocoa" do |ss|
    ss.dependency "Moya/ReactiveSwift"
end
```

**Comment by BasThomas** [comment]
The current Podfile seems to work. Did what [I thought](https://github.com/Moya/Moya/pull/805#issuecomment-263545349) would work. Can anyone confirm? `pod lib lint` runs fine (although it takes a really long time 😮)

**Comment by ashfurrow** [comment]
Yup, it takes a long time because it needs to run every permutation of every subspec. This is great, the only change I would add is the modify the Podfile used in the Demo project to reference the new subspec. Great work!

**Comment by BasThomas** [comment]
Done. 👍

**Pull request merged**
