### PR TITLE
Updated multipart body building for 2.2 and 2.3

### PR DESCRIPTION
**Pull request by mattfxyz**
These changes were already implemented and merged in PR #581.

Brought up in Issue #580, the changes were never added to a Swift 2.2 and 2.3 releases, meaning MultipartFormBody was broken for release 7.x

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool, I'd love to get another set of eyes on this, and we can release tomorrow. Thanks for taking this on!

**Comment by ashfurrow** [comment]
Ok, I'll get this released as soon as possible, I'll let you know 👍

**Comment by ashfurrow** [comment]
Okay, this should be up. @mattfxyz can you confirm this works on your end?

**Comment by mattfxyz** [comment]
@ashfurrow Looks like cocoapods is aware of new version but there isn't a release. I can release it if you want.

But I pointed my podfile at the release-7.0.4 branch and everything is working as planned!

**Comment by ashfurrow** [comment]
Right! I had to release manually instead of using the rake task, if you could create the GitHub release that would be :100:

**Comment by mattfxyz** [comment]
@ashfurrow Release created and our podfile update!

**Comment by mattfxyz** [comment]
@ashfurrow Release created and our podfile update! I'll close the issue.

**Pull request merged**
