### PR TITLE
Add documentation to clarify how carthage deals with submodules

### LINKED ISSUE #1427: Is it possible to install Moya/ReactiveMoya via Carthage without installing RxSwift?
Moya 10.0.0
ReactiveSwift 2.0.1

It does not seem possible to install `ReactiveMoya` via carthage without also installing `RxMoya` and `RxSwift` (and probably also `RxBlocking`, `RxCocoa`, and `RxTests`).

Adding ReactiveMoya to Carthage

```ruby
github "Moya/ReactiveMoya" 
```

and running `carthage update ReactiveMoya --platform iOS` produces this error:

```bash
A shell task (/usr/bin/env git checkout --quiet 7ec3c37331e939c1fa07cc3445fa4c0cb47f524f (launched in /path/to/Carthage/Checkouts/ReactiveMoya/External/Moya)) failed with exit code 128:
fatal: reference is not a tree: 7ec3c37331e939c1fa07cc3445fa4c0cb47f524f
```

If I add the following instead:
```ruby
github "Moya/Moya" ~> 10.0 
```
but don't copy the `Rx*` frameworks to my build phases, I get the following error at runtime:

```bash
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /path/to/Frameworks/Moya_ObjectMapper.framework/Moya_ObjectMapper
  Reason: image not found
```

The runtime issue may be a problem with `Moya-ObjectMapper` specifically, but regardless, I don't see a way to build `ReactiveMoya` without all the `Rx*` dependencies.

### PR DESCRIPTION
**Pull request by JohnTheBastard**
Fixes #1427

Carthage doesn't provide a way to build only required submodules. Added explanation to clarify this difference from Cocoapods.

### CODE REVIEW

**Comment by JohnTheBastard** [comment]
Is there anything else I need to do for this to be merged? (I don't have write access, so can't do it myself.)

**Comment by SD10** [comment]
Hey @JohnTheBastard, we usually wait for ~2 people to approve any given pull request before merging. I don't know anything about Carthage so I can't sign off on this but I'm sure another qualified Moya contributor will give their input when available

**Comment by JohnTheBastard** [comment]
Got it, no problem. Thanks!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by JohnTheBastard** [comment]
Glad to help!

**Pull request merged**
