### PR TITLE
Fixed compilation issues with the demo project, tests and reactive extensions

### PR DESCRIPTION
**Pull request by jarrodrobins**
This set of commits fixes a bunch of compilation issues that the Swift 2 branch has had. 

Even better - the tests work again! (Excluding ReactiveCocoa, more on this below)

1. Fixed up the Moya+RxSwift and Moya+ReactiveCocoa compilation issues with the change from NSError -> ErrorType (as I mentioned in my last PR at https://github.com/Moya/Moya/pull/207) 

2. With the release of Xcode 7 GM, Alamofire decided to move fast and break things by deleting their Swift 2 branch. I've updated the Podfile to point at master.

3. Fixed a compilation issue in the demo project.

4. Running `make test` spat out a heap of issues, all errors due to changes in Swift 2 over the Xcode 7 beta. I've updated the Quick and Nimble pods and fixed the issues. 

I should point out that in https://github.com/Moya/Moya/commit/3b46ef81f55d9f906a0fea8c7fa67889ce1eee19 ReactiveCocoa was commented out due to incompatibility. As such, I've commented out the tests that use ReactiveCocoa until the incompatibilities are fixed. 

This PR might look rather large but it's mostly down to the fact that Moya has the Pod directory committed. (As per https://github.com/Moya/Moya/pull/147)

Also I should say - thanks for adding me as a collaborator, Ash! I'll leave you or someone else to merge this in (probably better to have someone look over it that isn't me at least.)

### CODE REVIEW

**Comment by jarrodrobins** [comment]
OK, looks like I spoke too soon on the tests. They run locally? :-P

I'm seeings lots of things like `use of undeclared type 'ErrorType'` - I'm guessing CI isn't using Swift 2?

**Comment by ashfurrow** [comment]
Hmm, seems likely. I'll see what I can do to reconfigure it.

**Comment by ashfurrow** [comment]
Thanks!

**Comment by ashfurrow** [comment]
I've merged this for now; will fix the errors and send a new PR so it's cleaner.

**Pull request merged**
