### PR TITLE
Fix unit test build failed

### PR DESCRIPTION
**Pull request by cruisediary**
Fix unit test build failed on Swift 4.2 👻

### CODE REVIEW

**Comment by cruisediary** [comment]
Please review this PR 😄

**Comment by SD10** [comment]
I was planning on doing a release yesterday but then I saw this PR. I need to check out this branch and compile Moya. I'm not sure why this didn't fail in #1740

**Comment by cruisediary** [comment]
@SD10 because #1740 Support Swift 4.2 with Xcode 10 below targets
- Moya
- Basic
- Multi-target

so after I change the version to 4.2 of MoyaTests target from 4.0 then test build failed on Moya:development branch 😄

**Comment by cruisediary** [comment]
💛

**Pull request merged**
