### PR TITLE
Test our Carthage support in CI

### PR DESCRIPTION
**Pull request by orta**
We should get the CI to keep track of our Carthage support, I debated putting this in danger but it takes a very long time to run, and when I ran it locally Xcode crashed :-/

screen shot 2016-09-14 at 6 11 16 pm

### CODE REVIEW

**Comment by orta** [comment]
Maybe it'll be better on CI

**Comment by ashfurrow** [comment]
Great idea!

**Comment by orta** [comment]
Dang, an extra 35m to run on each CI run. Wonder if it's worth adding Jenkins _just_ for doing this instead of putting it on the real CI.

Anyway, we _know_ master is broken, this just validates it. Happy to either rebase with master isn't broken.

**Comment by ashfurrow** [comment]
I'm not surprised master isn't working, the 7.0.x stuff branched off from the 7.0.0 tag, and all the Swift 3 stuff is in its own branch, so master has been languishing for a bit. 

We could consider only testing one platform with Carthage, instead of iOS, macOS, watchOS, and tvOS. It might be worth the time tradeoff, not sure. What do you think?

**Comment by orta** [comment]
I'd be OK with just doing iOS, if we can - once some of the other PRs are in, I'll look at the docs to see if I can do that

**Comment by ashfurrow** [comment]
Great work! I think keeping Carthage support working is an acceptable tradeoff for a slower CI, thanks Orta.

**Pull request merged**
