### PR TITLE
[WIP] Single scheme

### LINKED ISSUE #818: Discuss: Use a single target for all platforms?
Hey all! I was reading https://blog.pusher.com/what-i-learned-building-the-pusherswift-framework/, and one of the first things the author goes into is how the framework they built uses only one target for all platforms. 

Currently Moya has 4 targets for each 3 of our frameworks (12 total), and then 3 for tests.
screen shot 2016-12-01 at 2 39 57 pm

I'm not sure how the author was able to make a universal target, but maybe we could do something similar?

### PR DESCRIPTION
**Pull request by gperdomor**
- Convert project to single schema target.
- Update deps for better swift 3.1 support.

Fix #818

### CODE REVIEW

**Comment by BasThomas** [comment]
What does this do over #967?

**Comment by gperdomor** [comment]
@BasThomas theoretically not much, the purpose is the same, but in this case i converted manually, without script.

Also i updated the dependencies for better compatibility with Swift 3.1 and remove some deprecation warnings... Demo was updated too.

This PR is target to 9.0.0

**Comment by pedrovereza** [comment]
I think we can take the deprecation warning in master, as it's not a breaking change. We actually have #1027 to do it :wink:

I also think that converting to a single scheme is not a breaking change and we should take it in master (which makes me think that we should continue #967 instead).

The dependencies update is good, but is it a breaking change? If not, I'd vote for merging into master so we can release it before 9.0

**Comment by gperdomor** [comment]
Closed in favor of #967

**Pull request closed without merging**
