### PR TITLE
Docs  translated into Chinese

### PR DESCRIPTION
**Pull request by lovesomeone**
The document is translated into simplified Chinese

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @lovesomeone. Thank you _so_ much for this PR. This is a great amount of work and we really appreciate that! 

However, I'm not sure that this translation belongs here. The amount of work we would have to do to maintain both documentations is quite big (especially if you look at how many open documentation issues are there, meaning there are not many people that want to take care of that).

I suggest that you can create your repository with Moya documentation in Chinese and we will point to that from our Readme. What do you think?

Also, I'm interested in other @Moya/contributors opinion.

**Comment by ashfurrow** [comment]
@lovesomeone this is amazing – thanks so much! 

I don't think it's too burdensome to keep the docs in this repo; our English docs drift behind our implementation and our contributors keep them up to date, I expect our Chinese-speaking contributors would be available to help too. Either way is fine 😄

**Comment by SD10** [comment]
I teared up when I saw this PR this morning 🤣 I think that having Chinese documentation is great! Anything that makes Moya more accessible to different developers is fine by me.

In regards to maintenance, it may be good to note that the Chinese documentation may not always be up to date and I think that our English documentation should only be a blocker for a breaking change.

Like Ash said, I'm sure our Chinese-speaking contributors will jump in and join the effort to keep things up to date.

@Moya/contributors and watchers: If you speak Chinese give this comment a 👍 so we can see how many contributors are fluent in the language 😃

**Comment by lovesomeone** [comment]
@sunshinejr. I think it's ok to have it in my repository first 。 if it help  then we can make merge。

**Comment by lovesomeone** [comment]
@sunshinejr. I think it's ok to have it in my repository first 。 if it help then we can make merge

@all    I really love this project and thank you very much for all of  your contribution。 Hope Moya becomes  better 。

By the way ， when I learn this project  ，I  think the documents are not well organized，especially   docs /README.md

**Comment by xiaoyaogaojian** [comment]
I'm a Chinese. English documents always took me longer time to read and sometimes, because of my poor English, even make me misunderstand something. So I think having the Chinese documents is helpful to make this project more accessible to Chinese-speaking developers and, in turn,  could attract more contributors to improve this project including keep the Chinese documents up-to-date.

**Comment by orta** [comment]
This is 🥇

**Comment by sunshinejr** [comment]
Okay, okay. Maybe my first take on this one was a bit premature - Chinese docs being a little bit behind  might not be a big problem if we state so. Let's just take a look at the content there and merge it if it's ready then 👍

**Comment by ashfurrow** [comment]
It looks like a few of the docs are incomplete – let's merge this, and then open an issue about how to indicate that they might be incomplete or behind, but we would appreciate any help.

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by lovesomeone** [comment]
I'm glad to be invited。Yes  ,I like this project . I‘m very happy that I can be one of contributors！

**Pull request merged**
