### PR TITLE
remove endpoint generics

### LINKED ISSUE #1524: Remove generics of Endpoint
I want to make a `PR` to remove generics of `Endpoint`. The reason based on:

`Endpoint` is a concrete class, and store some basic info about request. I cannot found any reason that `Endpoint` need uses generics.

Maybe my thoughts is one-sided, please let me know if it is.:beers::beers:

### PR DESCRIPTION
**Pull request by zhongwuzw**
Fixes #1524

### CODE REVIEW

**Comment by freak4pc** [comment]
@zhongwuzw What problem does this PR solve, except for the "pure" aspect of that Concrete class not necessarily needing Target? There might be other developers who count on expecting Endpoints of certain Targets as inputs of classes, etc. Seems like a bit of a breaking change for no real benefit, unless I'm missing out. 

I believe the original author of that class would be @ashfurrow - if you have a few seconds to say what you think about this, and what was the original reasoning behind using a Generic here, that might be helpful :)

**Comment by ashfurrow** [comment]
Hmm, yeah I'm undecided here. I think there _was_ once a reason to have the `Endpoint` type be generic but it's beyond me now. I've looked through [Eidolon](https://github.com/artsy/eidolon) and can't find any use of the generics, and there's not any member in the `Endpoint` type that even references the generic. 

So on philosophical grounds, I think this PR is good. However, it's hard to say what the impact could be for the larger community. Additionally, there's code churn to be concerned with; this is a big change and I don't want to give the community a bunch of work to do without having a concrete benefit in mind. I mean, it's not a lot of work to migrate, but it _is_ work, and it _is_ a breaking change, so we'd need to roll this into Moya 11.0.

So I'm kind of split on this. I like the idea of removing the generic for code hygiene reasons, but I worry about unintended impact and code churn. Hopefully others who are more active users of Moya than I am can chime in about how they feel about it. Hope that context helps.

**Comment by SD10** [comment]
I think the PR is good too. However, I can’t see any positive gains from doing so other than clean code. The generic is resolved at compile time so there shouldn’t be any performance boosts.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@ashfurrow How do you recommend Moya handles code churn going forward? I realize it's important given the maturity of the project, but Moya was also built over 4 years of an unstable Swift.

For example, we still have class methods on MoyaProvider because a generic type couldn't have a nested type. 

Though important now, maybe this becomes even more important when Swift itself reaches ABI stability?

**Comment by sunshinejr** [comment]
I see the value of this PR in terms of cleaner `endpoint`/`endpointClosure`, but as others stated I'm not sure it outweighs the cons from migration/relying on the generic part of an Endpoint. We would have to investigate it a bit more to see what really would happen after the flattening.

**Comment by zhongwuzw** [comment]
@SD10 , Aside `Endpoint`, `Generics` would increase build time. In this situation of `Endpoint`, we need two steps, one is to find wether we need generics in `Endpoint` in some situations(by now, I can not found, maybe it has but rarely), another step is to investigate that how we can handle this in these situations.

@sunshinejr , yep, I love clean code😊, if we just need in rarely situations, I think we should remove it, because it leads to many useless code, build time, and increase executable size because specialization if we not need generics at all.

**Comment by SD10** [comment]
@zhongwuzw I don't expect this to significantly impact build times, even on a large project using Moya, but it is relevant.

Honestly, the migration for this is trivial. That does not worry me in the slightest. I just want to figure out if it is possible for someone to be relying on the generic before removing it. We need to figure out if it has any meaning.

**Comment by SD10** [comment]
Ironically, I found an issue #434 Endpoint doesn't need to be generic by @ashfurrow 🤣

**Comment by ashfurrow** [comment]
That's pretty funny – looks like #434 was closed and merged into #556, but _that_ discussion itself didn't lead to changes and we never reconsidered #434. After a year and a half, I'm glad we're finally wrapping that up!

**Comment by SD10** [comment]
@ashfurrow I've been keeping track of all the changes to the English docs that are not reflected in the Chinese docs in #1357. Last week I released Moya 11.0.0-beta.1, should this change be merged before the official release of 11.0?

@zhongwuzw How about I take care of the documentation Ash has requested since my native language is English and you can translate them into Chinese for me?

**Comment by ashfurrow** [comment]
If we already have a major release in the works, I would recommend prioritizing this change and shipping it in the next beta.

**Comment by zhongwuzw** [comment]
@SD10 , 💯 I'll updated Chinese docs after you updated the English docs.

**Comment by SD10** [comment]
I got it @BasThomas. So sorry, I will really do this today.

- [ ] CHANGELOG
- [ ] Docs
- [ ] Migration Guide
- [ ] Inline Endpoint Docs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No pressure @SD10!

**Comment by SD10** [comment]
Alright, really really sorry for the delays. I completed the checklist I made above. 

I updated all the occurrences of the `Endpoint` generic in the `docs_CN` directory as well @zhongwuzw. So there doesn't seem to be anything to translate to Chinese. We could use the `docs/migration_10_to_11.md` translated but that seems like it should be another issue.

**Comment by SD10** [comment]
We had a lot of input on this one. Let me know if everything looks good to merge and we can get this merged into 11.0.0 ⛵️

**Comment by Jeroenbb94** [comment]
We did use the generic on our project but just as @ashfurrow mentioned, we don't know the reason anymore. The migration from 10 to 11 was easily done and our unit test still work without changing them.

**Comment by sunshinejr** [comment]
@Jeroenbb94 Thank you very much for this feedback! We didn't hear any in beta stage so each report is really valuable to us.

**Pull request merged**
