### PR TITLE
Fix Xcode 10.2 warnings

### PR DESCRIPTION
**Pull request by larsschwegmann**
Xcode 10.2 introduced some new warnings, which this PR fixes

### CODE REVIEW

**Comment by pedrovereza** [comment]
Hey @larsschwegmann thanks for taking the time to fix these warnings 🙏 

Can you rebase your branch against `development` and change the target branch for this pr to also be `development`?

**Comment by larsschwegmann** [comment]
Sure, will do! 😄👍🏻

**Comment by BasThomas** [comment]
Can we release a new version that includes this patch? :)

**Comment by sunshinejr** [comment]
@BasThomas yeah gonna release current development tomorrow, just need few adjustments beforehand. Tracking it in #1823.

**Comment by larsschwegmann** [comment]
Thanks for helping me out @sunshinejr 😄

**Pull request merged**
