### PR TITLE
fix Carthage Instructions

### PR DESCRIPTION
**Pull request by Lutzifer**
The additional Repositories no longer seen to exist, but everything is included in Moya/Moya

### CODE REVIEW

**Comment by pedrovereza** [comment]
This was introduced recently in f90429587b92a57d33ed7019fc80b5a082aac7b2.

@BasThomas Any reason why we'd want to keep them separated in the instructions? 🤔

**Comment by scottrhoyt** [comment]
I think it may have just been a copying error from the Cocoapods instructions.

**Comment by pedrovereza** [comment]
@scottrhoyt Yea, that may be the case. Just wanted to double check with him because these changes normally come after a PR/issue and maybe there was a discussion we don't remember.

**Comment by BasThomas** [comment]
I think I misunderstood the instructions and made an error here. Thanks for fixing this, @Lutzifer! 🙌

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Pull request merged**
