### PR TITLE
Readme copyedits

### PR DESCRIPTION
**Pull request by BasThomas**
This adds some small fixes to the README.

### CODE REVIEW

**Comment by BasThomas** [comment]
Where does the `Contributing.md` needs updating? I think it's already reflecting the current state.

**Comment by sunshinejr** [comment]
@BasThomas Oh, I meant that Contributing.md is copied from our contributors repository and we probably need to update that repository too.

**Comment by BasThomas** [comment]
But I only changed the README? :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sunshinejr** [comment]
Damn it, I swear I saw Contributing.md on my phone, seems like I’m done for today :D

**Comment by BasThomas** [comment]
Awesome, thanks for the approvals!

**Pull request merged**
