### PR TITLE
Update to RxSwift 6

### PR DESCRIPTION
**Pull request by peagasilva**
This PR:
- updates the RxSwift dependency to the 6.0 version;
- adds a [`carthage.sh`](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) script to workaround a Carthage issue - it's also used for running the tests through `rake`;
- updates CircleCI's `Xcode` version to `11.7.0` (the last version with `Swift 5.2`);
- updates test versions: `iOS` to `13.7` and `tvOS` to `13.4` (both from `13.3`); 
- adds implicitly the `expression` parameter in the `expect` method usage to fix ambiguity;
- updates the `Changelog.md` file.

The dependencies `Alamofire`, `OHHTTPStubs`, `Nimble` and `ReactiveSwift` were also updated as a result from running the `./scripts/carthage.sh build --platform iOS` command.

### CODE REVIEW

**Comment by jdisho** [comment]
LGTM, but the CI is failing because of SwiftLint. Mind having a look there? 😊

**Review by jdisho — CHANGES_REQUESTED** [review]
LGTM, but the CI is failing because of SwiftLint. Mind having a look there? 😊

**Comment by LucianoPAlmeida** [comment]
Looking through the failed build logs, the problem seems not with swift lint but with danger. In there we see some requests failing initially and the some fails in the https://docs.github.com/en/free-pro-team@latest/rest/reference/search#rate-limit 

cc @f-meloni 
Ping since it could be a problem on danger swift or some related :)

**Comment by xygkevin** [comment]
Hello , May I ask when the upgrade will be completed?
RxSwift 6.0.0
Swift 5.3

**Comment by peagasilva** [comment]
The [log](https://app.circleci.com/pipelines/github/Moya/Moya/129/workflows/f52720a0-4311-4506-801b-01b707ba7f09/jobs/4031) @LucianoPAlmeida mentioned.

**Comment by kristiyandobrev** [comment]
@peagasilva 

Any specific reason for not using latest `Quick` and `Nimble` versions ?

**Comment by peagasilva** [comment]
Not really @kristiyandobrev. As the focus was to update the RxSwift dependency, I didn't intentionally touch the other dependencies.

**Comment by ageevvalentin** [comment]
Any updates? When will it be merged? More than a month has passed since the release of RxSwift 6.0. 
Is the project not supported?

**Comment by lordzsolt** [comment]
As @LucianoPAlmeida said, it's Danger that is failing.

@jdisho  Could the CI get fixed, instead of blocking this PR? I would like to remove the workaround of referencing a forked version...

**Comment by AndrewSB** [comment]
hey! I'm going to merge this today. @peagasilva got any final changes? I'm going to re-run CI to see if I can figure out what's going on with rake/danger

**Comment by peagasilva** [comment]
@AndrewSB there are no further changes. Thanks!

**Comment by AndrewSB** [comment]
this error just shows up 19 times

```
Cloning and building inline dependencies: import DangerSwiftProse // package: https://github.com/f-meloni/danger-swift-prose.git, import DangerXCodeSummary // package: https://github.com/f-meloni/danger-swift-xcodesummary.git, this might take some time.
Updating packages...
Using https://github.com/f-meloni/danger-swift-prose.git latest major:1
Updating packages...
Using https://github.com/f-meloni/danger-swift-xcodesummary.git latest major:1
Updating packages...

Failing the build, there are 19 fails.
Request failed [422]: https://api.github.com/repos/Moya/Moya/pulls/2120/comments
Response: {
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequestReviewComment",
      "code": "invalid",
      "field": "position"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-review-comment-for-a-pull-request"
}
```

looks like a rate limiting issue. I'm going to go ahead and merge this for now, and if this doesn't solve itself, or is a legitimate breakage, I'll move these changes to a branch and revert master

**Comment by LucianoPAlmeida** [comment]
> this error just shows up 19 times
> 
> ```
> Cloning and building inline dependencies: import DangerSwiftProse // package: https://github.com/f-meloni/danger-swift-prose.git, import DangerXCodeSummary // package: https://github.com/f-meloni/danger-swift-xcodesummary.git, this might take some time.
> Updating packages...
> Using https://github.com/f-meloni/danger-swift-prose.git latest major:1
> Updating packages...
> Using https://github.com/f-meloni/danger-swift-xcodesummary.git latest major:1
> Updating packages...
> 
> Failing the build, there are 19 fails.
> Request failed [422]: https://api.github.com/repos/Moya/Moya/pulls/2120/comments
> Response: {
>   "message": "Validation Failed",
>   "errors": [
>     {
>       "resource": "PullRequestReviewComment",
>       "code": "invalid",
>       "field": "position"
>     }
>   ],
>   "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-review-comment-for-a-pull-request"
> }
> ```
> 
> looks like a rate limiting issue. I'm going to go ahead and merge this for now, and if this doesn't solve itself, or is a legitimate breakage, I'll move these changes to a branch and revert `development`

@AndrewSB A hint I have is that danger prose was causing the issue, because it seems like it issues to may requests to GitHub API and GitHub now implements a rate limit  https://docs.github.com/en/free-pro-team@latest/rest/reference/search#rate-limit maybe we could disable it for now and see if it solves the issue.
But is just a guess, didn't investigate properly :)

**Comment by AndrewSB** [comment]
that sounds like a great guess! does danger prose have a repository? can we create an issue there and have them verify our assumption? we must not be the only project seeing this

**Comment by LucianoPAlmeida** [comment]
> that sounds like a great guess! does danger prose have a repository? can we create an issue there and have them verify our assumption? we must not be the only project seeing this

I have to check but I think we use swift-danger prose https://github.com/f-meloni/danger-swift-prose, I remember one set of PR's where we move to all swift on danger :)

**Comment by pchmelar** [comment]
Thanks for the merge, when we can expect release of 15.0.0 ? 🙂

**Comment by PierreBrisorgueil** [comment]
@AndrewSB +1 possible release of 15.0.0-alpha.2 to get an official tag RxSwift 6.x (6.0.0 6.1.0) 
on ten dependencies all I need is the moya switch :)

**Pull request merged**
