### PR TITLE
Removed .gitmodules

### PR DESCRIPTION
**Pull request by justinmakaila**
Related to #534. Tested in local repo and got through `carthage update` no problem.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Looks like it was checked in here, in October 2015: https://github.com/Moya/Moya/commit/9ee73026ba8e2bf4394de7d795ba42b778b3fea7#diff-8903239df476d7401cf9e76af0252622 so the problem this PR solves has been around since about [version 4.1.0](https://github.com/Moya/Moya/blob/master/Changelog.md#410) of Moya. @justinmakaila Do you think this is something worth including in the changelog? Like, would it be useful for Carthage users to have a note in there about it?

**Comment by justinmakaila** [comment]
@ashfurrow I don't think so, everything looks fine for downloading the build with carthage with and without submodules. I think it made it in as a mistake and became a problem somewhere between then and now as `Carthage` progressed.

**Comment by ashfurrow** [comment]
Okay cool. The only CI failure is a missing changelog, so I'm going to merge (and then submit a PR changing that "no changelog" error to a warning...)

**Comment by orta** [comment]
> Okay cool. The only CI failure is a missing changelog, so I'm going to merge (and then submit a PR changing that "no changelog" error to a warning...)

Might want to check for App-level changes before failing instead

**Comment by ashfurrow** [comment]
Hmm, good idea. I added the error originally to help us be more diligent about our changelog entries. I still worry that if we keep the error, we might intimidate new contributors with a failed CI build instead of a warning. And longtime contributors are [even getting called out](https://github.com/Moya/Moya/pull/530#issuecomment-231434087). Going to move discussion over to https://github.com/Moya/Moya/pull/537

**Pull request merged**
