### PR TITLE
Updated Cartfile and Moya.podspec to use RAC4 release 

### PR DESCRIPTION
**Pull request by Austinate**
Only problematic part i see now — only 4.0.0 RC2 is available at Pods Spec repo

### CODE REVIEW

**Comment by Austinate** [comment]
Also probably we should bump Moya version since RC4 update but i'm not sure yet, so decided to delay that change

**Comment by ashfurrow** [comment]
Cool. This is only failing because the RAC podspec wasn't pushed until like an hour ago. I'm going to re-run CI.

**Comment by Austinate** [comment]
:+1:

**Comment by ashfurrow** [comment]
Cool, this has been released as 6.1.3 on CocoaPods and as a GitHub release.

**Pull request merged**
