### PR TITLE
Change .Underlying to NSError, add error handling docs

### PR DESCRIPTION
**Pull request by Paldom**
According to #478

### CODE REVIEW

**Comment by ashfurrow** [comment]
Super cool, this looks awesome! Could you add an entry to the top of the changelog?

**Comment by Paldom** [comment]
Sure, I've added the following:
> Changes `Moya.Error.Underlying` to have `NSError` instead of `ErrorType`.

**Comment by ashfurrow** [comment]
Looks good! Weird that CI is failing, I'll take a look when I get a chance.

**Comment by ealeksandrov** [comment]
Restarted CI, it is green now.
PR looks good for me, great work!

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by Paldom** [comment]
It's a pleasure :)

**Pull request merged**
