### PR TITLE
[WIP] Configure codecov reporting

### PR DESCRIPTION
**Pull request by swizzlr**
This PR introduces codecov support to the repo.

To do:
- [ ] Verify this works, exclude coverage sections as necessary
- [ ] Configure failure modes with codecov
- [ ] Update changelog?
- [ ] Add a badge to the repo

### CODE REVIEW

**Comment by esttorhe** [comment]
Looks good to me; does this provide some kind of `badge` with the coverage to put on the `README` perhaps?

**Comment by swizzlr** [comment]
I bet we can rustle one up!

**Comment by esttorhe** [comment]
I like this and don't think this will introduce any breaking changes so I'm merging it. :+1:

**Comment by swizzlr** [comment]
Cheers :+1:

**Pull request merged**
