### PR TITLE
Update Releasing.md with few additional steps to "After release" paragraph.

### PR DESCRIPTION
**Pull request by sunshinejr**
This includes few additional steps that I usually do after the release. Also, I totally forgot about our [jazzy-generated docs](https://moya.github.io) and I think everyone did 😄 Already updated the docs and gonna try to add a danger check as well in a few minutes.

### CODE REVIEW

**Comment by sunshinejr** [comment]
I've cancelled the builds as this is just a doc change and I forgot about adding `[skip ci]` in the commit message 🤦‍♂

**Comment by sunshinejr** [comment]
Now that I think about it, Danger would need to add this message on every PR as we not only need to regenerate docs on docs changes, but also comments/code updates depending on the change. Wonder if we could automate a commit to master to regenerate the docs on [moya.github.io](https://github.com/Moya/moya.github.io) 🤔

**Comment by f-meloni** [comment]
@sunshinejr Don't know if can help but on Danger we automatically re-generate the docs on every release.
https://github.com/danger/swift/blob/master/Package.swift#L57

**Comment by sunshinejr** [comment]
@f-meloni oh nice! do you think it would be possible to regenerate docs on separate repo in the same org?

**Comment by f-meloni** [comment]
@sunshinejr `Rocket` just runs steps that can be written in bash or swift (+ has some pre defined steps).
Then I think that potentially can.
For example if you look in Danger after the release it does

```
"after": [
    "Scripts/create_homebrew_tap.sh",
]
```

That pulls and updates the Danger homebrew repo

**Comment by sunshinejr** [comment]
@f-meloni alright, I've created an issue for that one so we do not forget about it 😉 #1864

**Pull request merged**
