### PR TITLE
Update installation instructions (version pinning)

### PR DESCRIPTION
**Pull request by BasThomas**
As discussed in #946

### CODE REVIEW

**Comment by BasThomas** [comment]
By the way, how do the Reactive extensions work with SwiftPM?

**Comment by pedrovereza** [comment]
I think we can keep it as `pod 'Moya'` (we always want people to be using the latest version, I feel)

**Comment by BasThomas** [comment]
Yeah, that might be even better. Does SwiftPM work like that as well?

**Comment by BasThomas** [comment]
It seems like we need to at least provide a `majorVersion` [there](https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#package-dependency).

**Pull request merged**
