### PR TITLE
Adds readme for web directory

### PR DESCRIPTION
**Pull request by ashfurrow**
Loosely related to #559.

WIP because GitHub is choosing not to render the `svg` tag.

### CODE REVIEW

**Comment by ashfurrow** [comment]
@orta suggestions for the best way to display these colours? This is what I'm going for:

screen shot 2016-07-23 at 1 56 36 pm

**Comment by orta** [comment]
My only known hack here doesn't work http://www.tizag.com/htmlT/bgcolor.php - https://gist.github.com/orta/62febeb573df8e52965a5af7ddf5ba17

**Comment by orta** [comment]
Images are the best way to go

**Comment by orta** [comment]
though the purple is massive, and the rest are the right sized, would recommend throwng in image optim too

**Comment by ashfurrow** [comment]
Okay, i think this is ready for review 👍

**Comment by orta** [comment]
Better fix all them swiftlintsssssssssssssssssssss

**Comment by ashfurrow** [comment]
Yup, working on it now. It's also running more than once.

**Comment by orta** [comment]
but nah, everything looks good from me.

One option for improvement though. You could do all the images at 2x size, then set the width/height to be half that. Then you have retina images. This is how I do it in most of my web projects.


screen shot 2016-07-23 at 9 29 03 pm

with 

screen shot 2016-07-23 at 9 28 23 pm

instead of this at full size:

screen shot 2016-07-23 at 9 29 28 pm

**Comment by ashfurrow** [comment]
okaaaaay

**Comment by orta** [comment]
It's a free TIL ;)

**Comment by orta** [comment]
Yep - that should do it

**Comment by ashfurrow** [comment]
I've opened https://github.com/Moya/Moya/pull/561 to address the SwiftLint problems.

**Pull request merged**
