### PR TITLE
Moya JASON Mapper update 

### PR DESCRIPTION
**Pull request by AvdLee**
I've updated the readme to link to [Moya-JASONMapper](https://github.com/AvdLee/Moya-JASONMapper) as this one is being update more often and tries to be in sync with Moya releases.

### CODE REVIEW

**Comment by AvdLee** [comment]
I'm getting the error: 
```
For your GitHub repo, you need to expose: DANGER_GITHUB_API_TOKEN
You may also need: DANGER_GITHUB_HOST, DANGER_GITHUB_API_BASE_URL
```

I've got my token ready, but I'm unable to expose it using the `DANGER_GITHUB_API_TOKEN` key. Anyone available to provide me the needed information to do this?

**Comment by pedrovereza** [comment]
> Suppressing export of environment variables DANGER_GITHUB_API_TOKEN fork PR builds

Not sure why Circle decided to skip this step, but that's what is causing the issue

**Comment by pedrovereza** [comment]
Got it: I had to enable **Pass secrets to builds from forked pull requests** in the settings.

**Comment by AvdLee** [comment]
We could do that. However, I think it's important that we reference the repo's who are up to date the most. When developing you want to reference up to date repo's as much as possible.

**Comment by BasThomas** [comment]
I agree with @AvdLee. Maybe @sunshinejr knows about any intended work on the former?

**Comment by pedrovereza** [comment]
> We could do that. However, I think it's important that we reference the repo's who are up to date the most. When developing you want to reference up to date repo's as much as possible.

Agreed, but I don't think that [Moya-JASON](https://github.com/DroidsOnRoids/Moya-JASON) is truly outdated at this point. [It is using Moya version 8.0.0-beta-4](https://github.com/DroidsOnRoids/Moya-JASON/blob/master/Moya-JASON.podspec#L33).

It's true that [Moya-JASONMapper](https://github.com/AvdLee/Moya-JASONMapper) is using 8.0.0-beta-6, but I wouldn't consider this a huge difference.

My suggestion is to keep both listed and let whoever needs a JASON mapper decide which one fits their needs.

**Comment by sunshinejr** [comment]
Woah, that's harsh. Didn't have time to update all the things lately, dunno when will it happen so can't promise anything. I'm gonna leave the decision to you guys.

**Comment by ashfurrow** [comment]
Listing both makes the most sense to me too. Moya has been moving very quickly and making a lot of breaking changes, it makes sense that the community is struggling to keep up. Hopefully things settle down a bit after our 8.0 release.

**Pull request merged**
