### PR TITLE
remove NetworkCurlLogger.swift from .xcodeproj

### LINKED ISSUE #525: master doesn't build currently
The file `NetworkCurlLoggerPlugin.swift` doesn't exist. Tried looking back in the logs & blame, couldn't find much about the file. May be related to #505?

### PR DESCRIPTION
**Pull request by AndrewSB**
fixes #525

### CODE REVIEW

**Comment by esttorhe** [comment]
@AndrewSB would you mind adding an entry to the `Changelog` ? 😄

**Comment by esttorhe** [comment]
Looks good and test are passing ✅

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by esttorhe** [comment]
I'll need some time to get used to the 🤖Ash from posting as soon as I hit the merge button 😛

**Comment by ashfurrow** [comment]
It worked! https://github.com/Moya/Aeryn

**Comment by AndrewSB** [comment]
thanks for the invite @ashfurrow 😄, I accepted!

All the new notifications I'm getting from Moya are a little crazy, but I love what you're trying to do setting up a community of people around Moya.

🔥

**Pull request merged**
