### PR TITLE
Update Basic.md

### PR DESCRIPTION
**Pull request by lzzhoujielun**
failure to  call  absoluteString() in the document

### CODE REVIEW

**Comment by jdisho** [comment]
Hmm, nothing against this PR, but I find a bit misleading that the parameter name is `url` and its expected type is `String`. Makes sense to change the type to `URL`? 🤔

**Comment by LucianoPAlmeida** [comment]
> Hmm, nothing against this PR, but I find a bit misleading that the parameter name is `url` and its expected type is `String`. Makes sense to change the type to `URL`? 🤔

@jdisho I think it does make sense, but I don't know if maybe there is an overload(to simplify calls) and there another that takes an URL? Not sure, but if it is the only one, change to URL makes sense but that would be a breaking change...

**Comment by sunshinejr** [comment]
@jdisho @LucianoPAlmeida I was actually surprised myself that we pass the `String` type, even though we still need to convert it to `URL` when passing to `URLRequest` afterwards. Not sure if there is anything against changing it the type to `URL` (besides the fact that people would need to update & need to release major version), but maybe we can try with a PR and see how it goes?

**Comment by LucianoPAlmeida** [comment]
> @jdisho @LucianoPAlmeida I was actually surprised myself that we pass the `String` type, even though we still need to convert it to `URL` when passing to `URLRequest` afterwards. Not sure if there is anything against changing it the type to `URL` (besides the fact that people would need to update & need to release major version), but maybe we can try with a PR and see how it goes?

@sunshinejr @jdisho Maybe to not be a breaking change, we can just add another overload with the same signature, just with URL type, without removing the string one, maybe just deprecate the string version... :)

**Pull request merged**
