### PR TITLE
Update Cartfile

### PR DESCRIPTION
**Pull request by wongzigii**
ReactiveSwift is released! 🎉

### CODE REVIEW

**Comment by ashfurrow** [comment]
This looks good, did you want to re-open it?

**Comment by wongzigii** [comment]
@ashfurrow ah, I have no idea why the test is failed.

**Comment by ashfurrow** [comment]
Sometimes the unit tests fail like that and someone has to restart the build. I've restarted it, if you want to re-open :+1: Thanks!

**Comment by wongzigii** [comment]
https://github.com/Moya/Moya/pull/674 
This pull request has been deleted, unfortunately.

**Pull request closed without merging**
