### PR TITLE
Support tvOS and watchOS

### LINKED ISSUE #241: Update podspec to support tvOS
A lot of pods are being updated to support tvOS and the latest RxSwift development branch has been updated as well. Unfortunately I investigated and found that you can't use specific branches in the podspec dependencies due to versioning issues so we might have to wait for the dependencies to work these changes into a tag. This library is a really great idea and I'd love to use it in a tvOS app I'm coding instead of manually wrapping Alamofire with RxSwift observables.

### PR DESCRIPTION
**Pull request by petester42**
This should close #241 when it is finalized. The carthage targets should work but I am seeing errors when I run `pod lib lint`. Not sure what to do about it. The error is as follows:

```
 -> Moya (4.3.1)
    - ERROR | [Moya/ReactiveCocoa] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [Moya/ReactiveCocoa] xcodebuild:  <module-includes>:2:9: note: in file included from <module-includes>:2:
    - ERROR | [Moya/ReactiveCocoa] xcodebuild:  /var/folders/z3/llmwqlln7pz907z5596pjct80000gp/T/CocoaPods/Lint/build/Release-watchsimulator/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:94:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found
    - NOTE  | [Moya/ReactiveCocoa] xcodebuild:  <unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
    - ERROR | [Moya/ReactiveCocoa] xcodebuild:  /var/folders/z3/llmwqlln7pz907z5596pjct80000gp/T/CocoaPods/Lint/build/Release-appletvsimulator/ReactiveCocoa.framework/Headers/ReactiveCocoa-Swift.h:94:9: error: 'ReactiveCocoa/ReactiveCocoa.h' file not found

[!] Moya did not pass validation, due to 3 errors.
You can use the `--no-clean` option to inspect any issue.
```

Besides that it should be ready to go. 

- Adds tvOS and watchOS support
- Fixes carthage OS X target not having source files
- Makes base OS X target 10.9 instead of 10.10

### CODE REVIEW

**Comment by ashfurrow** [comment]
Looks :100: I have an idea about the lint failures – will let you know.

**Comment by ashfurrow** [comment]
Hmm. No dice here. Looks like it's problems with RAC on the watch/tv platforms. I'll try to look into it shortly.

**Comment by ashfurrow** [comment]
Getting the same errors. Makes me think it's a problem I made with the podspec. I'll take a look at it tomorrow with @orta and see if we can get this merged.

**Comment by orta** [comment]
Sure thing, hit me up when you get in to the office

**Comment by orta** [comment]
Alright, so it looks like the watch isn't getting `ReactiveCocoa/ReactiveCocoa.h` - it's likely from [this](https://github.com/ashfurrow/ReactiveCocoa/blob/v4.0-alpha.3-podspec/ReactiveCocoa.podspec#L48) subspec not providing a watch/tvos reference to the source files.

I did something like this for [Artsy Authentication](https://github.com/artsy/Artsy-Authentication/blob/17ceee99c3b3170a49b5fca7f7650f94f40e1de9/Artsy%2BAuthentication.podspec#L26).

**Comment by ashfurrow** [comment]
I've pushed up an updated podpsec to trunk that should deal with the problems: https://raw.githubusercontent.com/CocoaPods/Specs/92a7990f1f521367d3c4a1274d3ca37564973054/Specs/ReactiveCocoa/4.0.3-alpha-3/ReactiveCocoa.podspec.json

**Comment by ashfurrow** [comment]
Validating now.

**Comment by ashfurrow** [comment]
screen shot 2015-11-06 at 10 15 58 am

**Comment by petester42** [comment]
:+1:

**Comment by ashfurrow** [comment]
Pushing up an update now.

**Comment by ashfurrow** [comment]
Alrighty! Moya now supports iOS, OS X, watchOS, and tvOS: https://raw.githubusercontent.com/CocoaPods/Specs/2589039691ec831ba080994a5f4387306260da22/Specs/Moya/4.4.0/Moya.podspec.json

Thanks for all the hard work @petester42!

**Pull request merged**
