### PR TITLE
Fix tests

### LINKED ISSUE #259: CI is Failing Intermittently
Not sure what caused it. Looks like a problem with Xcode (go figure).

```
The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(1 failure)
2015-10-22 00:38:04.847 xcodebuild[769:3065] [MT] IDETestOperationsObserverDebug: (357FE833-30CF-44F9-9DD3-7F464EB8F250) Beginning test session with Xcode 7A220 on target <DVTiPhoneSimulator: 0x7f99c2cdecf0> {
		SimDevice: SimDevice : iPhone 6 (CEBBD79A-B6C1-4A02-BD33-56BBCBDED03E) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 9.0 (13A340) - com.apple.CoreSimulator.SimRuntime.iOS-9-0 }
} (9.0 (13A340))
2015-10-22 00:38:33.992 xcodebuild[769:4353] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f99c33d1c20>
Testing failed:
	Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
** TEST FAILED **
```

### LINKED ISSUE #349: Fix CI

### PR DESCRIPTION
**Pull request by ashfurrow**
_Hopefully_, this will fix the intermittent false negative on CI. I also removed all the unnecessary async testing (we never really need to use `toEventually` in our case).

Additionally, I changed the release task to accommodate [this issue](https://github.com/CocoaPods/CocoaPods/issues/4326) and cleaned up some matchers.

Fixes #349.
Fixes #259.

### CODE REVIEW

**Comment by ashfurrow** [comment]
This is an interesting PR (humblebrag) specifically from a unit testing perspective; I'm happy to answer questions or clarify changes made to our use of matchers, etc.

@Moya/contributors this would also be a good "first PR review" if someone out there hasn't reviewed+merged one before.

**Comment by swizzlr** [comment]
I wonder if the world would benefit from RAC factoring out the Scheduling library into its own framework.

**Comment by ashfurrow** [comment]
Open an issue – they seem to be all about small libraries.

**Comment by petester42** [comment]
Everything looks good aside of a couple syntax fixes. Let's hope it fixes the CI problems.

**Comment by ashfurrow** [comment]
I _think_ I've addressed all the feedback; GitHub isn't collapsing it since it's on the commits instead of the PR ¯\\_(ツ)_/¯

**Comment by petester42** [comment]
From what I understood from @orta's comment is that we will be able to set the `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS` environment variable in the podfile with cocoapods 1.0. So I'll merge this and open an issue to fix the `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS` issue when cocoapods reaches 1.0.

Good job :100:

**Pull request merged**
