### PR TITLE
Fix several translation errors and punctuation errors in Vision_CN.md

### PR DESCRIPTION
**Pull request by tamarous**

### CODE REVIEW

**Comment by tamarous** [comment]
@ashfurrow Hi, can you help me with this [CI check issue](https://app.circleci.com/pipelines/github/Moya/Moya/310/workflows/69de93dd-0e9b-4851-a334-aedf57a4a0ab/jobs/4399)? In this pr, I updated the Vision_CN.md, which was just some documentation modifications, but it failed when tested with Carthage. I logged in to the CircleCI but I don't have write permission to the project, so I cannot rerun the job.

**Comment by ashfurrow** [comment]
I've restarted the build. Looks like an intermittent problem with Carthage. If it fails again, we can merge without CI being green. (Sorry for the delay.)

**Comment by tamarous** [comment]
> I've restarted the build. Looks like an intermittent problem with Carthage. If it fails again, we can merge without CI being green. (Sorry for the delay.)

Looks like it failed again. So can you please force merge it? Thank you. @ashfurrow

**Comment by ashfurrow** [comment]
Okay, I'm going to merge. If `master` builds start failing on Carthage, then those are legit failures that would have started after any PR merge, so we'll have to fix those. Hopefully this was just a fluke, though!

**Comment by ashfurrow** [comment]
Unfortunately, CI is now failing on `master`. This is definitely not your fault! I've opened #2245 to address this. Thanks again for your contribution!

**Pull request merged**
