### PR TITLE
Bump ReactiveSwift to 5.0 and Result to 4.1

### PR DESCRIPTION
**Pull request by larryonoff**
Bump ReactiveSwift to 5.0 and Result to 4.1

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @larryonoff, thanks for the PR! Was there something specific that happened in `Result` 4.1 that we don't want to support version 4.0?

**Comment by larryonoff** [comment]
@sunshinejr ReactiveSwift 5.0 depends on Result 4.1. 

ReactiveSwift 5.0 and Result 4.1 both add Swift 5.0 and Xcode 10.2.

**Comment by sunshinejr** [comment]
@larryonoff makes sense, thanks! Would you please update SPM lock (probably `swift package update` if I'm not mistaken)? 

+ I see that the project doesn't want to build tests due to Alamofire update... Interestingly enough it seems like they've made a breaking change without a major update 🤔

**Comment by larryonoff** [comment]
@sunshinejr done

**Comment by larryonoff** [comment]
@sunshinejr 
> I see that the project doesn't want to build tests due to Alamofire update... Interestingly enough it seems like they've made a breaking change without a major update 🤔

I'm not sure, but it was without update.

**Comment by sunshinejr** [comment]
@larryonoff when you look at the `Cartfile.resolved` (we use Carthage dependencies for building/testing), you can see that the Alamofire has bumped version to 4.8.1. Then, when we look at the build error in tests:
```swift
❌  /Users/distiller/Moya/Moya/Tests/EndpointClosureSpec.swift:65:19: method does not override any method from its superclass

    override func upload(multipartFormData: @escaping (Alamofire.MultipartFormData) -> Void, usingThreshold encodingMemoryThreshold: UInt64, with urlRequest: URLRequestConvertible, encodingCompletion: ((SessionManager.MultipartFormDataEncodingResult) -> Void)?) {
```

it seems like Alamofire updated this method in their minor/patch release. If you have time to fix this one it would be great! If not, I could try to look around and help you out so no worries 👍

**Comment by larryonoff** [comment]
@sunshinejr I have fixed it in the current branch. Please review

**Pull request merged**
