### PR TITLE
Adds Vision document

### LINKED ISSUE #1081: Vision document / FAQ
Do you think we, @Moya/contributors, can create a Vision document? This would help us create some clear goals for the project as well as giving the community and users a better idea of what we expect of this project going forward.

What do you think? And more concrete: what should be in it?

FAQ: 
Separating subspecs into repositories
Model decoding: soon with Apple's APIs
https://github.com/Moya/Moya/issues/1126#issuecomment-312125039

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a draft of the vision document requested in #1081 to help guide project direction. I want to make sure we cover everything, so please only consider this a starting point for the community to guide from here. I've also tried to include the history of the project to contextualize the goals.

@Moya/contributors your input would be welcome 🙇

Fixes #1081.

### CODE REVIEW

**Comment by SD10** [comment]
Maybe add [#1126 comment](https://github.com/Moya/Moya/issues/1126#issuecomment-312125039):
- favor explicitly defined behavior over default implementations

There are also a couple other things mentioned in #1081. Such as object decoding.

This document heavily refers to `requests` but doesn't talk about the `responses`. 

Currently, I wouldn't say Moya is in the business of response handling -- aside from providing a few `Moya.Response` extensions. But what's the vision for this? Are we for or against this behavior?

**Comment by BasThomas** [comment]
Two other small things:

- we might want to reference to the Vision document in (at least the) Readme.
- for consistency call the document `Vision.md` (instead of `VISION.md`) - or update all top level files to use uppercase.

**Comment by ashfurrow** [comment]
Okay, cool. Good ideas everyone – I've made some changes and pushed.

**Comment by mikesanderson** [comment]
Hey, I think this is great. Thanks @ashfurrow and @orta for founding this and staying involved. 

I think the Project Goals list could be easier to grasp by adjusting the order, grouping the goals starting with "provide..." together and ordering in a progression from requests to responses to customization and extension. I went ahead and committed the edit-- easier to show the result than describe it. Let me know. 

@orta the no caps / full stops gets me to, but I can't think of a solution that doesn't look worse. I think each has an implicit "Moya will..." or "First goal is to..." and that makes it work the way it is.

**Comment by ashfurrow** [comment]
Okay, I've un-WIP'd this PR. Going to give a few extra days for @Moya/contributors to chime in.

**Comment by pedrovereza** [comment]
I think the suggestion from @SD10 is valid:
> Maybe add #1126 comment:
> favor explicitly defined behavior over default implementations

He also raised a good question on what's our vision regarding responses in general:

> Currently, I wouldn't say Moya is in the business of response handling -- aside from providing a few Moya.Response extensions. But what's the vision for this? Are we for or against this behavior?

**Comment by ashfurrow** [comment]
@pedrovereza makes sense, I'll amend for the first point. I added something for response handling already, let me know what you think @SD10.

**Comment by pedrovereza** [comment]
@ashfurrow Sorry, I totally missed the response part on the document 🙈

**Pull request merged**
