### PR TITLE
[WIP] Swift 2.0

### LINKED ISSUE #156: Swift 2.0 branch?
I want to integrate Moya into an Xcode 7/Swift 2.0 project. Any chance of an official branch to support this to go along with the Alamofire swift-2.0 branch?

### PR DESCRIPTION
**Pull request by esttorhe**
# Fix #156 

This is still a WIP but wanted to create the `PR` anyways.
I tried tackling the `ReactiveCocoa` task but it proved harder than expected due to its `LlamaKit` dependency and it being stuck on `1.2` and no work to migrate to `2.0` is being made.

I went down the :rabbit: hole and this is a major rework I think.
So far `Moya` compiles on the `Demo` project with the current `Podfile` that's leaving `ReactiveCocoa` and `RxSwift` out of it (only core is being integrated).

This is what's done so far.

## Done:
- Currently using Quick and Nimble `swift-2.0` branches
- AlamoFire `swift-2.0` branch as well
- Moya Core is compiling
- Minimal Swift 2.0 migration (not reworked; only made it compile)
- @garethknowles migrated the code for `RxSwift`

## TODO:
- [ ] Migrate `ReactiveCocoa` to `swift2` branch
  - [ ] Generate a `podspec` for `swift2` branch first
    - ~~Migrate `LlamaKit` to `Swift2` :scream:~~ <-- `LlamaKit` is no longer a dependency
- [x] ~~Migrate `RxSwfit`~~

### CODE REVIEW

**Comment by ashfurrow** [comment]
Awesome, thanks!

**Comment by esttorhe** [comment]
I think I accidentally left my current take of `ReactiveCocoa.podspec` in there (I'm migrating the `JSON` file to a proper podspec but is less than WIP ATM)
)

**Comment by ashfurrow** [comment]
no problem :) Probably a good idea.

**Comment by alcarvalho** [comment]
That's great! And there's someone working on the migration of RxSwift
already.

Maybe we'll have soon. ;)

**Comment by garethknowles** [comment]
https://github.com/ashfurrow/Moya/pull/167

I have looked at getting Moya (specifically for RxSwift) working with swift 2.0.
Using the new Xcode 7.3 beta and by totally ignoring ReactiveCocoa, I think I've managed to get Moya working with swift 2.0.

It seems to be working well in my own project but I haven't got the Demo project and its tests working. I also had problems with ReactiveCocoa due to Carthage setup which I'm not very familiar with.

The main concern for me is the return defer in Moya+RxSwift.swift due to the changes which won't allow defer's to return.  I don't really see the need for a defer anyway so have simply replaced with a return closure.

Nonetheless, hopefully this might help with the migration over to 2.0

**Comment by esttorhe** [comment]
@garethknowles I rebased your branch into mine and updated the code in this `PR` to keep it under unified. 

The demo currently compiles and runs (although I didn't check the code if `RxSwift` was being used anywhere).

Sadly the tests won't run because of the `ReactiveCocoa` issue; I'll try to leave them out in the meantime to have a passing build

**Comment by alcarvalho** [comment]
Great, thank you!

Now the tests are failing because some files are pointing to the absolute path on someone's computer. Maybe yours?

```
⌦  unable to read module map contents from 'Target Support Files/Pods-Alamofire/Pods-Alamofire.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “Pods-Alamofire.modulemap” couldn’t be opened because there is no such file." UserInfo=0x7feb2a75bdc0 {NSFilePath=/Users/distiller/Moya/Demo/Pods/Target Support Files/Pods-Alamofire/Pods-Alamofire.modulemap, NSUnderlyingError=0x7feb2a7768f0 "The operation couldn’t be completed. No such file or directory"}
```

This `/Users/distiller/Moya/Demo/Pods/Target Support Files/Pods-Alamofire/Pods-Alamofire.modulemap` folder is inside someone's home folder. :wink:

**Comment by esttorhe** [comment]
That's not my username but I think its because of me; give me a sec

**Comment by esttorhe** [comment]
@alcarvalho I pushed a change to the `Podfile` pointing `Alamofire` to its github path and to the `swift-2.0` branch instead of a relative path.

**Comment by alcarvalho** [comment]
Are the tests working on your machine? From the log I can see now is matter configuring the correct version of XCode on the `circleci.yml` file. But this could be just the beginning. :worried:

**Comment by esttorhe** [comment]
What tests specifically?

If you open the `Demo` project on this branch and hit `Command + U` the test won't work because there are a bunch of `ReactiveCocoa` tests there and `ReactiveCocoa` imports and that part is not yet migrated to `Swift 2.0`.

I'm currently working on having a `podspec` that works with their `swift2` branch but I'm getting a `CocoaPods` crash locally that I'm trying to fix first.

**Comment by alcarvalho** [comment]
I see. After you get the tests running locally we'll need to see what is the correct XCode 7 version for Circle CI, if they support it already. Just to make sure the tests are passing there too.

**Comment by vCrespoP** [comment]
First of all, thanks to all contributors and of course the author :D

Any news with Swift 2.0? I still see in the fork that Alamofire is not pointing to the right version thus not compiling with xCode 7 beta 4. 

In order to set Alamofire correctly, this is an extract of my podfile:
pod 'Alamofire',
    :git => 'https://github.com/Alamofire/Alamofire.git',
    :branch => 'swift-2.0'

I know they may remove that branch, but for now maybe is convenient to point there in sift 2.0 branch?

Thanks for your effort!

**Comment by ashfurrow** [comment]
Hey there @vCrespoP! I'm not sure the status – I've not been using Swift 2 yet, but that will change soon, so I'll have some work time to devote to it.

**Comment by esttorhe** [comment]
Sadly (or for our own safety) we can't point `podspec` dependencies to specific branches and that's why I left all dependencies on this `PR` without version specific tags.

If you take a look at the `Demo` `Podfile` you'll see it like this:

```ruby
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

#pod 'ReactiveCocoa', :git => "https://github.com/reactivecocoa/reactivecocoa.git", :branch => "swift2"
pod 'RxSwift', :git => "https://github.com/kzaher/RxSwift.git", :branch => "feature/swift2.0"
pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire", :branch => "swift-2.0"

pod 'Moya/RxSwift', :path => "../"
#pod 'Moya/ReactiveCocoa', :path => "../"
pod 'Moya', :path => "../"

target 'DemoTests' do

  pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-2.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble', :branch => 'swift-2.0'
  pod 'OHHTTPStubs'

end
```

That's in order to satisfy the `Swift 2.0` requirements that can't be specified on the `podspec`.
As for `ReactiveCocoa` haven't had the time to tinker with the custom made `podspec` to point to a `Swift 2.0` branch and thus, the status on that front is still the same :snowflake:

**Comment by vCrespoP** [comment]
Thanks for your feedback guys, I will do that in the meantime.

I find this framework really interesting and meets my philosophy quite well, so keep up the good work and let's spread it :D

Cheers.

**Comment by ashfurrow** [comment]
Hey @esttorhe – could you close this, rebase from `master`, then submit a _new_ PR into Moya's `swift-2.0` branch?

**Comment by esttorhe** [comment]
@ashfurrow I'm headed out to get my :eyes: checked and won't be able to use the computer for 3-4 hours.

I'll close and rebase later today or tomorrow morning tops.

**Comment by ashfurrow** [comment]
Cool, thanks!

**Comment by esttorhe** [comment]
FYI started this late last night with my eye sight barely functioning and couldn't get too far due to my :eyes: being too tired.

Today is a brand new day :city_sunset: and I'll hope to have this done by _EOD_ today

**Comment by ashfurrow** [comment]
Take your time! The last thing we want is for you to get strained and burn out on open source :)

**Comment by esttorhe** [comment]
The rebase is done; I'm going to close this issue BUUUUUUUUT

I can't compile on ß5; getting the following

```console
Module file was created by an older version of the compiler; rebuild 'Security' and try again: /Applications/Xcode-7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/Security.swiftmodule
```

**Comment by esttorhe** [comment]
Or maybe I won't because I'll need to rename the branch or something else in order for Github to let me open a new `PR` (can't from the same `branch`)

**Comment by ashfurrow** [comment]
I've had that happen before. Silly GitHub. 



Maybe rename your branch, push, then PR into `swift-2`?

**Comment by esttorhe** [comment]
I did it!!
---

**Pull request closed without merging**
