### PR TITLE
Added installation step for Carthage in Readme.

### PR DESCRIPTION
**Pull request by karthikdash**
Hello,

This is my first open source contribution. 
Hope I have done this right.

With reference to #1210.

Thanks

### CODE REVIEW

**Comment by BasThomas** [comment]
Awesome, thanks @karthikdash! 🙌
Congratulations on your first contribution 😃

**Comment by sunshinejr** [comment]
PR looks good, thanks @karthikdash! You also did it to 9.0.0-dev, thanks! 🎉 

However, I'm not sure whether it resolves the issue. From the conversation in the issues referenced I'm not sure what the Carthage installation step should look like. I guess that it was connected to Moya/Reactive extensions versions? 🤔 Could you make a short description/todo-list in the issue, @BasThomas?

**Comment by karthikdash** [comment]
I think the issue #1208 was with the dependency of ReactiveSwift. The user was enforcing a lower version.

I am not sure what addition @BasThomas wanted.

**Comment by BasThomas** [comment]
I *think* the issue has to do with incompatible Moya / ReactiveSwift versions; so it is kind of unrelated.

I am now going to the process of setting up an app with Moya via Carthage to check if everything works as expected.

**Comment by ashfurrow** [comment]
Thanks a lot for contributing to Moya! I've invited you to join the Moya GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/Moya/contributors) and feel free to reach out with any questions.

**Comment by karthikdash** [comment]
Thank you for you support everyone! Looking forward to contribute :)

**Pull request merged**
