### PR TITLE
Merges master into swift-3.0 branch

### PR DESCRIPTION
**Pull request by ashfurrow**
There's been a lot of activity on master while we've been focused on Swift 3.0. Gotta merge 'em in! After making sure I didn't make any mistakes resolving the merge conflicts.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Tests are passing locally from the command line, too: 

screen shot 2016-09-15 at 9 52 02 pm


Going to try Carthage while I'm at it. CI is 🔴 because of an issue with Circle, I'm waiting on a response in their community forum.

**Comment by orta** [comment]
Giphy

**Comment by orta** [comment]
screen shot 2016-09-15 at 23 12 36

ran it from scratch on a fresh computer - all 👍 🍏

**Comment by edwardvalentini** [comment]
When I run on my local machine all tests pass too -- I'm currently trying on travis and tests fail however

**Pull request merged**
