### PR TITLE
Add Task case to handle request with Encodable type. #1325

### PR DESCRIPTION
**Pull request by LeLuckyVint**
Added new enum case for Encodable type

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @LeLuckyVint, thanks for getting this one up! There are few more things before we can merge, though:
- Handling transformation from `endpoint` to `urlRequest` [here](https://github.com/Moya/Moya/blob/master/Sources/Moya/Endpoint.swift#L66)
- Handling performing the request [here](https://github.com/Moya/Moya/blob/aedd30604d78ac231b9aa295f021681ea62fd4da/Sources/Moya/MoyaProvider%2BInternal.swift#L93)
- Adding a test case around [here](https://github.com/Moya/Moya/blob/aedd30604d78ac231b9aa295f021681ea62fd4da/Tests/EndpointSpec.swift#L127)
- Adding a changelog entry (you can checkout our guidelines [here](https://github.com/Moya/contributors/blob/master/Changelog%20Guidelines.md))
- At the end check if do not have any issues with SwiftLint

The behavior of `requestJsonEncodable` vs `requestData` is very similar, so you can try to base your implementation on that one. If you'll need help in anything, we'll be happy to assist!

**Comment by LeLuckyVint** [comment]
@sunshinejr i have a problem with associated value that confirms protocol `Equatable`.
When I want to create `Data` using `JSONEncoder` with associated value Xcode I have en error
screen shot 2017-09-29 at 1 13 28 pm

This is described in this [thread](https://www.reddit.com/r/swift/comments/6qha9l/why_can_i_not_use_a_protocol_in_the_method/)

**Comment by sunshinejr** [comment]
Oh yeah, this is the tricky one @LeLuckyVint. I believe we would have to think about this - the problem is that we can't use `Encodable` and generic in the case. One solution that comes to my mind is making a type eraser on it. Maybe you have any other idea how to fix that one, @LeLuckyVint?

**Comment by SD10** [comment]
Hey @LeLuckyVint, I just wanted to check if the status has changed on this one at all. It's one of the last things left to do for `v10.0` 😃 Thank you!

**Comment by LeLuckyVint** [comment]
@SD10 can you look into it, please. I have all tests passed on my local machine, but CI is failing and the errors are confusing

**Comment by sunshinejr** [comment]
Hey @LeLuckyVint. Thank you so much for this one! Unfortunately there were still few things to do before this would be merged. And because we want to release new version pretty soon, I finished it while giving credits to you and @afonsograca that also did a similar PR. I would love it if you could review my PR #1349 and let me know what do you think!

**Pull request closed without merging**
