### PR TITLE
Add Moya 10 to 11 migration guide

### LINKED ISSUE #1520: Create a Moya 11.0 migration guide
The next version will have very few API breaking changes but I believe it's still a good policy to put out a migration guide. I'll create one this weekend and try to move forward with the release.

### PR DESCRIPTION
**Pull request by SD10**
This resolves #1520. 

I think we should release a `11.0.0-beta.1` for a week and then do a hard `11.0.0` if all goes well.

### CODE REVIEW

**Comment by sunshinejr** [comment]
This looks good! I'm just thinking if we should add some info that this release needs major upgrade of ReactiveSwift as well. What do you think?

About releases - I'm cool with it. No need for an alpha I think, and one week beta should be enough, as we did it before and worked fine.

**Comment by SD10** [comment]
@sunshinejr Sorry for the slow turnaround. I added a link to the ReactiveSwift 3.0.0 release notes.

Regarding #1521, I'm fine with that but I haven't had the time to review it and we need more eyes on it. I don't want to be making decisions on new functionality or API breaking changes myself.

**Comment by sunshinejr** [comment]
@SD10 okay, cool. As much as I'd love to have this plugin in Moya 11, I don't really have much time for it either. Thus, I'm gonna merge this one and we could try with beta I guess!

**Comment by SD10** [comment]
This would be good to translate to Chinese as well. #1357

**Pull request merged**
